using IceFebruary;
using IceFebruary.Physics;
using IceFebruary.Time;
using UnityEngine;
using UnityIceFebruary;

public sealed class UnityGameAssembler : MonoBehaviour
{
    [SerializeField] private GameAssemblerConfig_AUTOGENERATED _config;

    private GameAssembler _gameAssembler;

    private void Awake()
    {
        GameAssemblerConfig config = _config.ToPoco();
        GameAssemblerSettings gameAssemblerSettings = config.Settings;

        ITime time = new UnityTime(gameAssemblerSettings.StartTimeCyclesBufferLength);
        IPhysics2D physics2D = new UnityPhysics2D(gameAssemblerSettings.StartPhysicsCollidersBufferLength);
        IObjectManager objectManager = new UnityObjectManager();

        UnityPlayerInputProvider playerInput = new(new());

        time.LaunchIFrame(playerInput);

        _gameAssembler = new(config.SpawnList, time, physics2D, objectManager, playerInput);

        _gameAssembler.Assemble();
    }
    private void Update() => _gameAssembler.Time.DoFrame(Time.deltaTime);
    private void FixedUpdate() => _gameAssembler.Time.DoFixedFrame();
}
