using IceFebruary;
using IceFebruary.Physics;
using IceFebruary.Time;
using UnityEngine;
using UnityIceFebruary;

public sealed class UnityGameAssembler : UnityBaseGameAssembler
{
    [SerializeField] private GameAssemblerConfig_AUTOGENERATED _config;
    private void Awake() => Assemble();
    protected override void Assembling()
    {
        GameAssemblerConfig config = _config.ToPoco();
        GameAssemblerSettings gameAssemblerSettings = config.Settings;

        ITime time = new UnityTime(gameAssemblerSettings.StartTimeCyclesBufferLength);
        IPhysics2D physics2D = new UnityPhysics2D(gameAssemblerSettings.StartPhysicsCollidersBufferLength);
        IObjectManager objectManager = new UnityObjectManager();

        UnityPlayerInputProvider playerInput = new(new());

        time.LaunchIFrame(playerInput);

        InnerAssembler = new InnerAssembler(config.SpawnList, time, physics2D, objectManager, playerInput);
    }
}
