//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class Component_IHingeJoint2D_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IHingeJoint2D_AUTOGENERATED _component;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _gameObject;
    public IceFebruary.Component<IceFebruary.Physics.IHingeJoint2D> ToPoco() => new IceFebruary.Component<IceFebruary.Physics.IHingeJoint2D>(_component == null ? default : _component.ToPoco(), _gameObject == null ? default : _gameObject.ToPoco());
}
