//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class AnimatorField_Boolean_AUTOGENERATED
{
    [UnityEngine.SerializeField] private AnimatorFieldData_AUTOGENERATED _animatorFieldData;
    public IceFebruary.Animation.AnimatorField<System.Boolean> ToPoco() => new IceFebruary.Animation.AnimatorField<System.Boolean>(_animatorFieldData == null ? default : _animatorFieldData.ToPoco());
}
