namespace UnityIceFebruary.AutoGeneration
{
    using IceFebruary.Proxy;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEditor;
    using UnityIceFebruary.AutoGeneration.Match;
    using UnityIceFebruary.AutoGeneration.Proxy;

    public class AutoGeneratorHandler : AssetPostprocessor
    {
        /// <summary>
        /// You can change a value of this field if you have to stop generate proxies.
        /// </summary>
        private static readonly bool _generateCodeAutomatically = false; 
        private static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedNames)
        {
            if (!_generateCodeAutomatically || !imported.Any(p => p.EndsWith(".cs") && !p.Contains("AutoGenerated") && !p.Contains("Proxy")))
                return;

            Generate();
        }

        [MenuItem("Tools/Generate all proxies")]
        public static void Generate()
        {
            HashSet<string> frameworkAssemblies = new()
            {
                typeof(IProxyAttribute).Assembly.GetName().Name,
                typeof(UnityAnalog).Assembly.GetName().Name
            };

            IEnumerable<Type> allTypes = AppDomain.CurrentDomain.GetAssemblies()
                .Where(a => !a.IsDynamic && (
                    frameworkAssemblies.Contains(a.GetName().Name) ||
                    a.GetReferencedAssemblies().Any(r => frameworkAssemblies.Contains(r.Name)) ||
                    a.GetName().Name == "Assembly-CSharp"
                ))
                .SelectMany(assembly => assembly.GetTypes());

            EditorApplication.delayCall += () =>
            {
                ProxyGenerator.Generate(allTypes);
                UnityMatchComponentGenerator.Generate(allTypes);
            };
        }
    }
}