namespace UnityIceFebruary.AutoGeneration
{
    using IceFebruary.Proxy;
    using System;
    using System.IO;
    using System.Text;
    using UnityEngine;

    public static class CSSaver
    {
        private static readonly string _autoCodeFolder = "AutoGenerated";
        private static string SavePath => Path.Combine(Application.dataPath, _autoCodeFolder);
        public static void SaveProxy(StringBuilder stringBuilder, Type classProxy) => SaveCSFile(stringBuilder, classProxy.Name.ToProxyName());
        public static void SaveCSFile(StringBuilder stringBuilder, string name)
        {
            string path = Path.Combine(SavePath, $"{name}.cs");

            if (!Directory.Exists(SavePath))
                Directory.CreateDirectory(SavePath);

            string content = stringBuilder.ToString();

            if (File.Exists(path) && File.ReadAllText(path) == content)
                return;

            File.WriteAllText(path, content);
        }
    }
}
