namespace UnityIceFebruary.AutoGenerator
{
    using IceFebruary.Proxy;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;

    public static class ProxyTypeExtensions
    {
        private static readonly BindingFlags _flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;
        public static string GetProxyName(this Type type) => $"{type.Name.Split('`')[0]}_{ScriptGenerator.AutogeneratedMark}";
        public static bool IsUnityAnalog(this Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(UnityBaseEntity<>);
        public static T GetAttribute<T>(this Type type) where T : Attribute
        {
            T attributeOnType = type.GetCustomAttributes<T>(true).FirstOrDefault();

            if (attributeOnType != null)
                return attributeOnType;

            return type
                .GetMembers(_flags)
                .Cast<MemberInfo>()
                .Concat(type.GetConstructors(_flags))
                .Select(member => member.GetCustomAttributes<T>(true).FirstOrDefault())
                .FirstOrDefault(attribute => attribute != null);
        }
        public static bool HasAttribute<T>(this Type type) where T : Attribute
        {
            if (type.GetCustomAttributes<T>(true).Any())
                return true;

            IEnumerable<MemberInfo> allMembers = type
                .GetMembers(_flags)
                .Cast<MemberInfo>()
                .Concat(type.GetConstructors(_flags));

            return allMembers.Any(member => member.GetCustomAttributes<T>(true).Any());
        }
        public static bool IsProxyable(this Type type) =>
            type.HasAttribute<FieldProxy>() ||
            type.HasAttribute<InterfaceProxy>() ||
            type.HasAttribute<Proxy>() ||
            type.HasAttribute<ScriptableObjectProxy>() ||
            type.IsUnityAnalog();
    }
}
