namespace UnityIceFebruary.AutoGenerator
{
    using UnityEditor;
    using UnityEngine;
    using System.Linq;
    using System.IO;
    using System;
    using System.Reflection;
    using IceFebruary.Proxy;

    public static class ProxyGenerator
    {
        public const string AutogeneratedMark = "AUTOGENERATED";
        [MenuItem("Tools/Generate scripts")]
        public static void Generate()
        {
            ProxyDirectory.RecoveryDirectories();

            Type[] types = Assembly.Load("Assembly-CSharp").GetTypes();

            string[] fileNames = Directory.GetFiles(Application.dataPath, "*.cs", SearchOption.AllDirectories)
                .Select(path => Path.GetFileNameWithoutExtension(path))
                .Where(path => !path.EndsWith(AutogeneratedMark))
                .ToArray();

            Type[] gameTypes = fileNames
                .Select(name => types.FirstOrDefault(type => type.Name == name))
                .Where(type => type != null)
                .OrderBy(type => GetPriority(type))
                .ToArray();

            Debug.Log($"Game types found in the assembly: {gameTypes.Length}");

            foreach (Type type in gameTypes)
            {
                string fileName = type.GetProxyName();

                if (type.HasAttribute<Proxy>())
                    Generate(typeof(Proxy), fileName, ProxyCodeBuilder.GetProxyCode(type));
                else if (type.HasAttribute<FieldProxy>())
                    Generate(typeof(FieldProxy), fileName, ProxyCodeBuilder.GetFieldProxyCode(type, type.GetAttribute<FieldProxy>()));
                else if (type.IsUnityAnalog())
                    Generate(typeof(UnityBaseEntity<>), fileName, ProxyCodeBuilder.GetUnityProxyCode(type));
                else if (type.HasAttribute<InterfaceProxy>())
                    Generate(typeof(InterfaceProxy), fileName, ProxyCodeBuilder.GetInterfaceProxyCode(type));
                else if (type.HasAttribute<ScriptableObjectProxy>())
                    Generate(typeof(ScriptableObjectProxy), fileName, ProxyCodeBuilder.GetScriptableObjectProxyCode(type));
            }

            Debug.Log("Done!");

            AssetDatabase.Refresh();
        }
        private static int GetPriority(Type type)
        {
            if (type.HasAttribute<InterfaceProxy>())
                return 1;
            return int.MaxValue;
        }
        private static void Generate(Type type, string fileName, string code)
        {
            string savePath = ProxyDirectory.GetPath(type);

            File.WriteAllText(Path.Combine(savePath, $"{fileName}.cs"), code);

            Debug.Log($"Proxy generated: {fileName}");
        }
    }
}
