namespace UnityIceFebruary.AutoGenerator
{
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.CSharp.Syntax;
    using System.Collections.Generic;
    using System.Linq;

    using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
    public static class ProxyBuilder
    {
        public static string GenerateInterfaceProxyCode(IEnumerable<SyntaxNode> nodes)
        {
            BaseNamespaceDeclarationSyntax namespaceDeclaration = nodes.OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();
            bool withoutNamespace = namespaceDeclaration == null;
            string namespaceName = withoutNamespace ? string.Empty : namespaceDeclaration.Name.ToString();
            UsingDirectiveSyntax usingDirective = withoutNamespace ? null : UsingDirective(ParseName(namespaceName));

            InterfaceDeclarationSyntax interfaceDeclaration = nodes.OfType<InterfaceDeclarationSyntax>().FirstOrDefault();
            string interfaceName = interfaceDeclaration.Identifier.Text;

            MethodDeclarationSyntax methodDeclaration = MethodDeclaration(IdentifierName(interfaceName), "ToPoco")
                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));

            InterfaceDeclarationSyntax proxyInterface = InterfaceDeclaration(interfaceName.GetProxyName())
                .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
                .AddMembers(methodDeclaration);

            CompilationUnitSyntax fileRoot = CompilationUnit();

            if (!withoutNamespace)
                fileRoot = fileRoot.AddUsings(usingDirective);

            fileRoot = fileRoot.AddMembers(proxyInterface);

            fileRoot = fileRoot.NormalizeWhitespace();

            return fileRoot.NormalizeWhitespace().ToFullString().AddWarning();
        }
        private static string GetProxyName(this string name) => $"{name}Proxy";
        private static string AddWarning(this string code) => $"// AUTOGENERATED. DO NOT EDIT.\n{code}";
    }
}
