namespace UnityIceFebruary.AutoGenerator
{
    using IceFebruary.Proxy;
    using System;
    using System.Reflection;

    public static class ProxyTypeExtensions
    {
        public static string GetProxyName(this Type type) => $"{type.Name.Split('`')[0]}_AUTOGENERATED";
        public static T GetAttribute<T>(this Type type) where T : Attribute => type.GetCustomAttribute<T>();
        public static bool IsUnityAnalog(this Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(UnityBaseEntity<>);
        public static bool HasAttribute<T>(this Type type) where T : Attribute => type.IsDefined(typeof(T), true);
        public static bool IsProxyable(this Type type) =>
            type.HasAttribute<FieldProxy>() ||
            type.HasAttribute<InterfaceProxy>() ||
            type.HasAttribute<Proxy>() ||
            type.HasAttribute<ScriptableObjectProxy>() ||
            type.IsUnityAnalog();
    }
}
