namespace UnityIceFebruary.AutoGenerator
{
    using UnityEditor;
    using UnityEngine;
    using System.Linq;
    using System.IO;
    using System;
    using System.Reflection;
    using IceFebruary.Proxy;

    public static class ProxyGenerator
    {
        public const string AutogeneratedMark = "AUTOGENERATED";
        [MenuItem("Tools/Generate scripts")]
        public static void Generate()
        {
            ProxyDirectory.RecoveryDirectories();

            Type[] types = Assembly.Load("Assembly-CSharp").GetTypes();

            string[] fileNames = Directory.GetFiles(Application.dataPath, "*.cs", SearchOption.AllDirectories)
                .Select(path => Path.GetFileNameWithoutExtension(path))
                .Where(path => !path.EndsWith(AutogeneratedMark))
                .ToArray();

            Type[] proxyableTypes = fileNames
                .Select(name => types.FirstOrDefault(type => type.Name == name))
                .Where(type => type != null && type.HasAttribute<GeneratorAttribute>())
                .OrderBy(type => GetPriority(type))
                .ToArray();

            Debug.Log($"Game types found in the assembly: {proxyableTypes.Length}");

            foreach (Type type in proxyableTypes)
            {
                GeneratorAttribute generatorAttribute = type.GetAttribute<GeneratorAttribute>();

                (Type attributeType, string code) = generatorAttribute switch
                {
                    Proxy => (typeof(Proxy), ProxyCodeBuilder.GetProxyCode(type)),
                    FieldProxy fieldProxy => (typeof(FieldProxy), ProxyCodeBuilder.GetFieldProxyCode(type, fieldProxy)),
                    InterfaceProxy => (typeof(InterfaceProxy), ProxyCodeBuilder.GetInterfaceProxyCode(type)),
                    ScriptableObjectProxy => (typeof(ScriptableObjectProxy), ProxyCodeBuilder.GetScriptableObjectProxyCode(type)),
                    _ => (null, null)
                };

                if (attributeType != null)
                    Generate(attributeType, type.GetProxyName(), code);
            }

            Debug.Log("Done!");
            AssetDatabase.Refresh();
        }
        private static int GetPriority(Type type)
        {
            if (type.HasAttribute<InterfaceProxy>())
                return 1;
            return int.MaxValue;
        }
        private static void Generate(Type type, string fileName, string code)
        {
            File.WriteAllText(Path.Combine(ProxyDirectory.GetPath(type), $"{fileName}.cs"), code);
            Debug.Log($"Proxy generated: {fileName}");
        }
    }
}
