namespace UnityIceFebruary.AutoGenerator
{
    using IceFebruary.Proxy;
    using System;
    using System.Linq;
    using System.Reflection;
    using System.Text;

    public static class ScriptBuilder
    {
        public static string GetInterfaceProxyCode(Type type)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.AppendLine($"public interface {type.GetProxyName()}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"\tpublic {type.FullName} ToPoco();");
            stringBuilder.AppendLine("}");

            return stringBuilder.ToString();
        }
        public static string GetFieldProxyCode(Type type, FieldProxy fieldProxy)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.AppendLine("[System.Serializable]");

            stringBuilder.Append($"public class {type.GetProxyName()}");

            Type fieldProxyInterface = fieldProxy.InterfaceType;

            if (fieldProxyInterface != null)
            {
                stringBuilder.Append(" : ");

                if (fieldProxyInterface.HasAttribute<InterfaceProxy>())
                    stringBuilder.AppendLine(fieldProxyInterface.GetProxyName());
                else
                    stringBuilder.AppendLine(fieldProxyInterface.FullName);
            }

            stringBuilder.AppendLine("{");

            ConstructorInfo constructor = type.GetConstructors().First();
            ParameterInfo[] parameters = constructor.GetParameters();

            foreach (ParameterInfo parameterInfo in parameters)
            {
                Type parameterType = parameterInfo.ParameterType;

                if (parameterType.IsInterface)
                    stringBuilder.Append("[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation]");
                else
                    stringBuilder.Append("[UnityEngine.SerializeField]");

                stringBuilder.Append(" private ");

                if (parameterType.IsProxyable())
                    stringBuilder.Append(parameterType.GetProxyName());
                else
                    stringBuilder.Append(parameterType.FullName);

                stringBuilder.AppendLine($" _{parameterInfo.Name};");
            }

            stringBuilder.Append($"public {type.FullName} ToPoco() => new(");

            stringBuilder.Append(string.Join(", ", parameters.Select(parameter => $"_{parameter.Name}")));

            stringBuilder.AppendLine(");");

            return stringBuilder.ToString();
        }
        public static string GetScriptableObjectProxy(Type type)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.AppendLine($"[UnityEngine.CreateAssetMenu(fileName = \"{type.Name}\", menuName = \"Proxy/{type.Name}\")]");

            stringBuilder.AppendLine($"public class {type.GetProxyName()} : UnityEngine.ScriptableObject");

            stringBuilder.AppendLine("{");

            ConstructorInfo constructor = type.GetConstructors().First();
            ParameterInfo[] parameters = constructor.GetParameters();

            foreach (ParameterInfo parameterInfo in parameters)
            {
                Type parameterType = parameterInfo.ParameterType;

                if (parameterType.IsInterface)
                    stringBuilder.Append("[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation]");
                else
                    stringBuilder.Append("[UnityEngine.SerializeField]");

                stringBuilder.Append(" private ");

                if (parameterType.IsProxyable())
                    stringBuilder.Append(parameterType.GetProxyName());
                else
                    stringBuilder.Append(parameterType.FullName);

                stringBuilder.AppendLine($" _{parameterInfo.Name};");
            }

            stringBuilder.Append($"public {type.FullName} ToPoco() => new(");

            stringBuilder.Append(string.Join(", ", parameters.Select(parameter => $"_{parameter.Name}")));

            stringBuilder.AppendLine(");");

            return stringBuilder.ToString();
        }
        private static string GetProxyName(this Type type) => $"{type.Name}_AUTOGENERATED";
    }
}
