//AUTOGENERATED. DO NOT EDIT.
[UnityEngine.CreateAssetMenu(fileName = "AreaScannerSettings", menuName = "Proxy/AreaScannerSettings")]
public sealed class AreaScannerSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IShape_AUTOGENERATED _shape;
    [UnityEngine.SerializeField] private System.Int32 _collidersMaxCount;
    [UnityEngine.SerializeField] private ContactFilter2D_AUTOGENERATED _contactFilter2D;
    public AreaScannerSettings ToPoco() => new AreaScannerSettings(_shape == null ? default : _shape.ToPoco(), _collidersMaxCount, _contactFilter2D == null ? default : _contactFilter2D.ToPoco());
}
