[UnityEngine.CreateAssetMenu(fileName = "CameraSettings", menuName = "Proxy/CameraSettings")]
public sealed class CameraSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeField] private System.Single _interpolation;
    [UnityEngine.SerializeField] private System.Single _minSize;
    [UnityEngine.SerializeField] private System.Single _maxSize;
    [UnityEngine.SerializeField] private System.Single _sensitivity;
    public CameraSettings ToPoco() => new CameraSettings(_interpolation, _minSize, _maxSize, _sensitivity);
}
