[UnityEngine.CreateAssetMenu(fileName = "EntityAnimatorDataProxy", menuName = "Proxy/EntityAnimatorData")]
public sealed class EntityAnimatorData_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private System.Int32 _walkAnimationHash;
	[UnityEngine.SerializeField] private System.Int32 _sneakAnimationHash;
	public EntityAnimatorData ToPoco() => new EntityAnimatorData(_walkAnimationHash, _sneakAnimationHash);
}
