[UnityEngine.CreateAssetMenu(fileName = "GrimaceLibraryProxy", menuName = "Proxy/GrimaceLibrary")]
public class GrimaceLibrary_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private Eyes_AUTOGENERATED[] _eyes;
	[UnityEngine.SerializeField] private Mouth_AUTOGENERATED[] _mouths;
	[UnityEngine.SerializeField] private Face _defaultFace;
	public GrimaceLibrary ToPoco() => new GrimaceLibrary(IceFebruary.Collections.GenericArraysExtensions.ToStructArray(System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_eyes ?? new Eyes_AUTOGENERATED[0], element => element?.ToPoco()))), IceFebruary.Collections.GenericArraysExtensions.ToStructArray(System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_mouths ?? new Mouth_AUTOGENERATED[0], element => element?.ToPoco()))), _defaultFace);
}
