[UnityEngine.CreateAssetMenu(fileName = "GroundCheckSettingsProxy", menuName = "Proxy/GroundCheckSettings")]
public sealed class GroundCheckSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IShape_AUTOGENERATED _groundCheckSize;
	[UnityEngine.SerializeField] private ContactFilter2D_AUTOGENERATED _contactFilter2D;
	public GroundCheckSettings ToPoco() => new GroundCheckSettings(_groundCheckSize.ToPoco(), _contactFilter2D.ToPoco());
}
