[UnityEngine.CreateAssetMenu(fileName = "GroundCheckSettingsProxy", menuName = "Proxy/GroundCheckSettings")]
public sealed class GroundCheckSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IceFebruary.Shapes.IShape _groundCheckSize;
	[UnityEngine.SerializeField] private IceFebruary.Physics.ContactFilter2D _contactFilter2D;
	public GroundCheckSettings ToPoco() => new GroundCheckSettings(_groundCheckSize, _contactFilter2D);
}
