[UnityEngine.CreateAssetMenu(fileName = "MouthProxy", menuName = "Proxy/Mouth")]
public sealed class Mouth_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IceFebruary.Render.ISprite _mouth;
	public Mouth ToPoco() => new Mouth(_mouth);
}
