[UnityEngine.CreateAssetMenu(fileName = "MovementSettingsProxy", menuName = "Proxy/MovementSettings")]
public class MovementSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private System.Single _speed;
	[UnityEngine.SerializeField] private System.Single _jumpForce;
	[UnityEngine.SerializeField] private System.Single _jumpBoost;
	public MovementSettings ToPoco() => new MovementSettings(_speed, _jumpForce, _jumpBoost);
}
