[UnityEngine.CreateAssetMenu(fileName = "MovementStatistickProxy", menuName = "Proxy/MovementStatistick")]
public sealed class MovementStatistick_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private System.Single _speed;
	[UnityEngine.SerializeField] private System.Single _jumpForce;
	[UnityEngine.SerializeField] private System.Single _jumpBoost;
	[UnityEngine.SerializeField] private System.Single _legsChangeRotationPeriod;
	[UnityEngine.SerializeField] private Rotor2_AUTOGENERATED _legRest;
	[UnityEngine.SerializeField] private Rotor2_AUTOGENERATED _legAmplitude;
	public MovementStatistick ToPoco() => new MovementStatistick(_speed, _jumpForce, _jumpBoost, _legsChangeRotationPeriod, _legRest.ToPoco(), _legAmplitude.ToPoco());
}
