[UnityEngine.CreateAssetMenu(fileName = "MovementStatistickProxy", menuName = "Proxy/MovementStatistick")]
public sealed class MovementStatistick_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private System.Single _speed;
	[UnityEngine.SerializeField] private System.Single _jumpForce;
	[UnityEngine.SerializeField] private System.Single _jumpBoost;
	public MovementStatistick ToPoco() => new MovementStatistick(_speed, _jumpForce, _jumpBoost);
}
