[UnityEngine.CreateAssetMenu(fileName = "PhysicsBalancerSettings", menuName = "Proxy/PhysicsBalancerSettings")]
public sealed class PhysicsBalancerSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRotor2Provider_AUTOGENERATED _target;
    [UnityEngine.SerializeField] private System.Single _force;
    public PhysicsBalancerSettings ToPoco() => new PhysicsBalancerSettings(_target == null ? default : _target.ToPoco(), _force);
}
