[UnityEngine.CreateAssetMenu(fileName = "PhysicsBalancerSettingsProxy", menuName = "Proxy/PhysicsBalancerSettings")]
public sealed class PhysicsBalancerSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IAngleProvider_AUTOGENERATED _target;
	[UnityEngine.SerializeField] private System.Single _force;
	public PhysicsBalancerSettings ToPoco() => new PhysicsBalancerSettings(_target.ToPoco(), _force);
}
