[UnityEngine.CreateAssetMenu(fileName = "PickUpStatisticksProxy", menuName = "Proxy/PickUpStatisticks")]
public sealed class PickUpStatisticks_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private System.Single _maxSqrPickUpDistance;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IShape_AUTOGENERATED _pickUpShape;
	public PickUpStatisticks ToPoco() => new PickUpStatisticks(_maxSqrPickUpDistance, _pickUpShape.ToPoco());
}
