[UnityEngine.CreateAssetMenu(fileName = "PickUpSettingsProxy", menuName = "Proxy/PickUpSettings")]
public sealed class PickUpSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private System.Single _maxSqrPickUpDistance;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IceFebruary.Shapes.IShape _pickUpShape;
	public PickUpSettings ToPoco() => new PickUpSettings(_maxSqrPickUpDistance, _pickUpShape);
}
