[UnityEngine.CreateAssetMenu(fileName = "PickUpSettings", menuName = "Proxy/PickUpSettings")]
public sealed class PickUpSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeField] private System.Single _maxSqrPickUpDistance;
    public PickUpSettings ToPoco() => new PickUpSettings(_maxSqrPickUpDistance);
}
