[UnityEngine.CreateAssetMenu(fileName = "PickUpSettingsProxy", menuName = "Proxy/PickUpSettings")]
public class PickUpSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeField] private System.Single _maxPickUpDistance;
	public PickUpSettings ToPoco() => new PickUpSettings(_maxPickUpDistance);
}
