[UnityEngine.CreateAssetMenu(fileName = "ProjectileSettings", menuName = "Proxy/ProjectileSettings")]
public sealed class ProjectileSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _prefab;
    [UnityEngine.SerializeField] private System.Single _objectLifeTime;
    public ProjectileSettings ToPoco() => new ProjectileSettings(_prefab == null ? default : _prefab.ToPoco(), _objectLifeTime);
}
