[UnityEngine.CreateAssetMenu(fileName = "ShootingSettings", menuName = "Proxy/ShootingSettings")]
public sealed class ShootingSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeField] private ProjectileSettings_AUTOGENERATED _projectileSettings;
    [UnityEngine.SerializeField] private System.Int32 _bulletsCount;
    [UnityEngine.SerializeField] private System.Single _shootingForce;
    [UnityEngine.SerializeField] private System.Single _recoilForce;
    [UnityEngine.SerializeField] private System.Single _cooldown;
    [UnityEngine.SerializeField] private System.Single _reloadCooldown;
    public ShootingSettings ToPoco() => new ShootingSettings(_projectileSettings == null ? default : _projectileSettings.ToPoco(), _bulletsCount, _shootingForce, _recoilForce, _cooldown, _reloadCooldown);
}
