[UnityEngine.CreateAssetMenu(fileName = "SpawnList", menuName = "Proxy/SpawnList")]
public sealed class SpawnList_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeField] private SpawnSettings_AUTOGENERATED _cameraSpawnSettings;
    [UnityEngine.SerializeField] private SpawnSettings_AUTOGENERATED _playerSpawnSettings;
    [UnityEngine.SerializeField] private SpawnSettings_AUTOGENERATED[] _enemiesSpawnSettings;
    [UnityEngine.SerializeField] private SpawnSettings_AUTOGENERATED[] _itemsSpawnList;
    public SpawnList ToPoco() => new SpawnList(_cameraSpawnSettings == null ? default : _cameraSpawnSettings.ToPoco(), _playerSpawnSettings == null ? default : _playerSpawnSettings.ToPoco(), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_enemiesSpawnSettings ?? new SpawnSettings_AUTOGENERATED[0], element => element.ToPoco())), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_itemsSpawnList ?? new SpawnSettings_AUTOGENERATED[0], element => element.ToPoco())));
}
