[UnityEngine.CreateAssetMenu(fileName = "StickmanSpawnList", menuName = "Proxy/StickmanSpawnList")]
public sealed class StickmanSpawnList_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _playerStickmanPrefab;
    [UnityEngine.SerializeField] private StickmanSpawnSettings_AUTOGENERATED _playerSpawnSettings;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _enemyStickmanPrefab;
    [UnityEngine.SerializeField] private StickmanSpawnSettings_AUTOGENERATED[] _enemiesSpawnSettings;
    public StickmanSpawnList ToPoco() => new StickmanSpawnList(_playerStickmanPrefab == null ? default : _playerStickmanPrefab.ToPoco(), _playerSpawnSettings == null ? default : _playerSpawnSettings.ToPoco(), _enemyStickmanPrefab == null ? default : _enemyStickmanPrefab.ToPoco(), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_enemiesSpawnSettings ?? new StickmanSpawnSettings_AUTOGENERATED[0], element => element.ToPoco())));
}
