[UnityEngine.CreateAssetMenu(fileName = "StickmanSpawnListProxy", menuName = "Proxy/StickmanSpawnList")]
public sealed class StickmanSpawnList_AUTOGENERATED : UnityEngine.ScriptableObject
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _stickmanPrefab;
	[UnityEngine.SerializeField] private StickmanSpawnSettings_AUTOGENERATED _playerSpawnSettings;
	[UnityEngine.SerializeField] private StickmanSpawnSettings_AUTOGENERATED[] _enemiesSpawnSettings;
	public StickmanSpawnList ToPoco() => new StickmanSpawnList(_stickmanPrefab.ToPoco(), _playerSpawnSettings.ToPoco(), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_enemiesSpawnSettings ?? new StickmanSpawnSettings_AUTOGENERATED[0], element => element.ToPoco())));
}
