namespace UnityIceFebruary
{
    using IceFebruary.Space.Vector2Provider;
    using UnityEngine;

    public class GameAssembler : MonoBehaviour
    {
        [Header("Base settings:")]
        [SerializeField] private int _startCyclesBufferSize = 128;
        [SerializeField] private int _overlapCollidersBufferLength = 64;
        [Header("Stickman settings:")]
        //[SerializeField] private StickmanSpawnList_AUTOGENERATED _stickmanSpawnList;

        private UnityTime _time;
        private UnityPhysics2D _physics2D;
        private UnityObjectManager _objectManager;

        private UnityPlayerInputProvider _input;

        private StickmanFactory _stickmanFactory;

        private void Awake()
        {
            _time = new(_startCyclesBufferSize);
            _physics2D = new(_overlapCollidersBufferLength);
            _objectManager = new();

            _input = new(new());

            _time.LaunchIFrame(_input);

            StickmanSpawnList stickmanSpawnList = new();//_stickmanSpawnList.ToPoco();

            _stickmanFactory = new(_time, _physics2D, _objectManager, stickmanSpawnList.StickmanPrefab);

            StickmanBuilder stickmanBuilder = _stickmanFactory
                .Create(stickmanSpawnList.PlayerSpawnsSetting.Position)
                .SetUp();
            
            stickmanBuilder.SetInput(_input);

            IVector2Provider playerStickmanConfig = stickmanBuilder.StickmanPosition;

            for (int index = 0; index < stickmanSpawnList.EnemiesSpawnSettings.Length; index++)
            {
                StickmanBuilder enemyBuilder = _stickmanFactory
                    .Create(stickmanSpawnList.EnemiesSpawnSettings[index].Position)
                    .SetUp();

                EnemyInputProvider enemyInputProvider = new(
                    enemyBuilder.StickmanPosition,
                    playerStickmanConfig);

                _time.LaunchIFrame(enemyInputProvider);

                enemyBuilder.SetInput(enemyInputProvider);
            }
        }
        private void Update() => _time.DoFrame(Time.deltaTime);
        private void FixedUpdate() => _time.DoFixedFrame();
    }
}
