namespace UnityIceFebruary
{
    using IceFebruary.Render;
    using IceFebruary.Space.Vector2Provider;
    using UnityEngine;
    using UnityIceFebruary.Components;

    public class GameAssembler : MonoBehaviour
    {
        [Header("Base settings:")]
        [SerializeField] private int _startCyclesBufferSize = 128;
        [SerializeField] private int _overlapCollidersBufferLength = 64;
        [SerializeField] private Camera _unityCamera;
        [Header("Stickman settings:")]
        [SerializeField] private StickmanSpawnList_AUTOGENERATED _stickmanSpawnList;

        private UnityTime _time;
        private UnityPhysics2D _physics2D;
        private UnityObjectManager _objectManager;

        private UnityPlayerInputProvider _input;
        
        private StickmanFactory _stickmanFactory;

        private void Awake()
        {
            _time = new(_startCyclesBufferSize);
            _physics2D = new(_overlapCollidersBufferLength);
            _objectManager = new();

            _input = new(new());

            ICamera camera = new UnityCamera(_unityCamera);

            _time.LaunchIFrame(_input);

            _stickmanFactory = new(_time, _physics2D, _objectManager);

            IVector2Provider playerCursor = new ScreenToWorldVector2Provider(
                new MouseVector2Provider(_input),
                camera);

            StickmanSpawnList stickmanSpawnList = _stickmanSpawnList.ToPoco();
            
            StickmanBuilder playerStickmanBuilder = _stickmanFactory.Create(
                stickmanSpawnList.PlayerStickmanPrefab,
                stickmanSpawnList.PlayerSpawnsSetting.Position);

            IVector2Provider playerStickmanPosition = playerStickmanBuilder.StickmanPosition;

            playerStickmanBuilder
                .SetLimbs()
                .SetMovement()
                .SetItemHolder(playerCursor)
                .SetInput(_input);

            for (int index = 0; index < stickmanSpawnList.EnemiesSpawnSettings.Length; index++)
            {
                StickmanBuilder enemyStickmanBuilder = _stickmanFactory.Create(
                    stickmanSpawnList.EnemyStickmanPrefab,
                    stickmanSpawnList.EnemiesSpawnSettings[index].Position);

                EnemyInputProvider enemyInput = new(
                    enemyStickmanBuilder.StickmanPosition,
                    playerStickmanPosition);

                IVector2Provider enemyCursor = new MouseVector2Provider(enemyInput);

                _time.LaunchIFrame(enemyInput);

                enemyStickmanBuilder
                    .SetLimbs()
                    .SetMovement()
                    .SetItemHolder(enemyCursor)
                    .SetInput(enemyInput);
            }
        }
        private void Update() => _time.DoFrame(Time.deltaTime);
        private void FixedUpdate() => _time.DoFixedFrame();
    }
}
