public static class UnityMatchObject //AUTOGENERATED
{
    public static readonly System.Collections.Generic.Dictionary<System.Type, System.Func<UnityEngine.Object, IceFebruary.IBaseEntity>> FabricAliases = new()
    {
        { typeof(UnityEngine.GameObject), obj => new UnityIceFebruary.UnityGameObject((UnityEngine.GameObject)obj) },
        { typeof(UnityEngine.Animator), obj => new UnityIceFebruary.Components.UnityAnimator((UnityEngine.Animator)obj) },
        { typeof(UnityEngine.Camera), obj => new UnityIceFebruary.Components.UnityCamera((UnityEngine.Camera)obj) },
        { typeof(UnityEngine.Collider2D), obj => new UnityIceFebruary.Components.UnityCollider2D((UnityEngine.Collider2D)obj) },
        { typeof(UnityEngine.HingeJoint2D), obj => new UnityIceFebruary.Components.UnityHingeJoint2D((UnityEngine.HingeJoint2D)obj) },
        { typeof(UnityEngine.Rigidbody2D), obj => new UnityIceFebruary.Components.UnityRigidbody2D((UnityEngine.Rigidbody2D)obj) },
        { typeof(UnityEngine.Transform), obj => new UnityIceFebruary.Components.UnityTransform((UnityEngine.Transform)obj) }
    };
    public static readonly System.Collections.Generic.Dictionary<System.Type, System.Type> UnityAnalogs = new()
    {
        { typeof(UnityEngine.GameObject), typeof(UnityIceFebruary.UnityGameObject) },
        { typeof(UnityEngine.Animator), typeof(UnityIceFebruary.Components.UnityAnimator) },
        { typeof(UnityEngine.Camera), typeof(UnityIceFebruary.Components.UnityCamera) },
        { typeof(UnityEngine.Collider2D), typeof(UnityIceFebruary.Components.UnityCollider2D) },
        { typeof(UnityEngine.HingeJoint2D), typeof(UnityIceFebruary.Components.UnityHingeJoint2D) },
        { typeof(UnityEngine.Rigidbody2D), typeof(UnityIceFebruary.Components.UnityRigidbody2D) },
        { typeof(UnityEngine.Transform), typeof(UnityIceFebruary.Components.UnityTransform) }
    };
}
