namespace UnityIceFebruary.Proxy
{
    using IceFebruary.Proxy;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Text;
    using UnityEditor;
    using UnityEngine;

    public static class ProxyGenerator
    {
        private static readonly string AutoGeneratedWarning = "// AUTO-GENERATED. DO NOT EDIT.";
        private static readonly string Serializable = "System.Serializable";
        private static readonly Dictionary<Type, string> _typeAlias = new()
        {
            { typeof(bool), "bool" },
            { typeof(byte), "byte" },
            { typeof(char), "char" },
            { typeof(decimal), "decimal" },
            { typeof(double), "double" },
            { typeof(float), "float" },
            { typeof(int), "int" },
            { typeof(long), "long" },
            { typeof(sbyte), "sbyte" },
            { typeof(short), "short" },
            { typeof(string), "string" },
            { typeof(uint), "uint" },
            { typeof(ulong), "ulong" },
            { typeof(ushort), "ushort" },
            { typeof(void), "void" }
        };

        [MenuItem("Tools/Generate all proxies")]
        public static void Generate()
        {
            List<Type> allTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(assembly => assembly.GetTypes())
                .ToList();

            IEnumerable<Type> generateInterfaceProxy = allTypes.Where(type => type.HasAttribute(out GenerateInterfaceProxy _));
            IEnumerable<Type> generateProxy = allTypes.Where(type => type.HasAttribute(out GenerateProxy _));
            IEnumerable<Type> generateScriptableObjectProxy = allTypes.Where(type => type.HasAttribute(out GenerateScriptableObjectProxy _));

            foreach (Type type in generateInterfaceProxy)
                GenerateInterfaceProxy(type);
            foreach (Type type in generateProxy)
                GenerateProxy(type);
            foreach (Type type in generateScriptableObjectProxy)
                GenerateScriptableObjectProxy(type);

            AssetDatabase.Refresh();

            Debug.Log("Proxy Generation Complete!");
        }
        private static void GenerateProxy(Type classProxy)
        {
            StringBuilder stringBuilder = new();
            GenerateProxy attribute = null;
            ConstructorInfo constructor = classProxy.GetConstructors().First(c => c.HasAttribute(out attribute));
            ParameterInfo[] parameters = constructor.GetParameters();
            Type interfaceType = attribute.InterfaceType;

            SetWarning(stringBuilder);

            SetUsings(stringBuilder, parameters);

            SetTitle(stringBuilder, classProxy, interfaceType, Serializable);

            stringBuilder.AppendLine("{");

            SetFields(stringBuilder, parameters);

            stringBuilder.AppendLine();

            SetConstructor(stringBuilder, interfaceType, classProxy, parameters);

            stringBuilder.AppendLine("}");

            SaveProxy(stringBuilder, classProxy);
        }
        private static void GenerateScriptableObjectProxy(Type scriptableObjectProxy)
        {
            StringBuilder stringBuilder = new();
            GenerateScriptableObjectProxy attribute = null;
            ConstructorInfo constructor = scriptableObjectProxy.GetConstructors().First(c => c.HasAttribute(out attribute));
            ParameterInfo[] parameters = constructor.GetParameters();

            SetWarning(stringBuilder);

            SetUsings(stringBuilder, parameters);

            SetTitle(stringBuilder, scriptableObjectProxy, typeof(ScriptableObject), GetProxyAssetMenu(scriptableObjectProxy));

            stringBuilder.AppendLine("{");

            SetFields(stringBuilder, parameters);

            stringBuilder.AppendLine();

            SetConstructor(stringBuilder, scriptableObjectProxy, scriptableObjectProxy, parameters);

            stringBuilder.AppendLine("}");

            SaveProxy(stringBuilder, scriptableObjectProxy);
        }
        private static void GenerateInterfaceProxy(Type interfaceProxy)
        {
            StringBuilder stringBuilder = new();

            SetWarning(stringBuilder);

            SetInterface(stringBuilder, interfaceProxy);

            SaveProxy(stringBuilder, interfaceProxy);
        }
        private static void SetWarning(StringBuilder stringBuilder) => stringBuilder.AppendLine(AutoGeneratedWarning);
        private static void SetUsings(StringBuilder stringBuilder, ParameterInfo[] parameters)
        {
            stringBuilder.AppendLine("using UnityEngine;");

            if (parameters.Any(parameter => parameter.ParameterType.IsGenericType))
                stringBuilder.AppendLine("using System.Collections.Generic;");

            if (parameters.Any(parameter => parameter.ParameterType.IsArray || parameter.ParameterType.IsList()))
                stringBuilder.AppendLine("using System.Linq;");

            stringBuilder.AppendLine();
        }
        private static void SetTitle(StringBuilder stringBuilder, Type classProxy, Type inheritType, string attribute = "")
        {
            if (!string.IsNullOrEmpty(attribute))
                stringBuilder.AppendLine($"[{attribute}]");

            stringBuilder.Append($"public class {classProxy.GetProxyName()}");

            if (inheritType != null)
                stringBuilder.AppendLine($" : {((inheritType.IsProxyableConstructors() || inheritType.IsInterfaceProxyable()) ? inheritType.GetProxyName() : inheritType.Name)}");
        }
        private static void SetFields(StringBuilder stringBuilder, ParameterInfo[] parameters)
        {
            foreach (ParameterInfo parameter in parameters)
                stringBuilder.AppendLine(GetField(parameter));
        }
        private static void SetConstructor(StringBuilder stringBuilder, Type classProxy, Type returnType, ParameterInfo[] parameters)
        {
            string classProxyName = classProxy.Name;
            string returnTypeName = returnType != null ? returnType.Name : classProxyName;

            stringBuilder.Append($"    public {returnTypeName} ToPoco() => new {classProxyName}(");

            IEnumerable<string> values = parameters.Select(parameter => GetProxyValue(parameter));

            stringBuilder.Append(string.Join(", ", values));
            stringBuilder.AppendLine(");");
        }
        private static void SetInterface(StringBuilder stringBuilder, Type interfaceProxy)
        {
            stringBuilder.AppendLine($"public interface {interfaceProxy.GetProxyName()}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    {interfaceProxy.Name} ToPoco();");
            stringBuilder.AppendLine("}");
        }
        private static string GetField(ParameterInfo parameter)
        {
            Type parameterType = parameter.ParameterType;
            string typeName = parameterType.GetSafetyTypeName();
            string stringAttribute = (parameterType.IsInterface || parameterType.IsAbstract) ? "[SerializeReference, InterfaceImplementation]" : "[SerializeField]";

            return $"    {stringAttribute} private {typeName} _{parameter.Name};";
        }
        private static string GetProxyValue(ParameterInfo parameter)
        {
            Type type = parameter.ParameterType;
            string parameterName = parameter.Name;

            if (type.IsProxyableConstructors() || type.IsInterfaceProxyable())
                return $"_{parameterName}.ToPoco()";
            if (type.IsList() && type.GetGenericArguments()[0].IsProxyableConstructors())
                return $"_{parameterName}.Select(x => x.ToPoco()).ToList()";
            if (type.IsArray && type.GetElementType().IsProxyableConstructors())
                return $"_{parameterName}.Select(x => x.ToPoco()).ToArray()";
            return $"_{parameterName}";
        }
        private static string GetSafetyTypeName(this Type type)
        {
            if (_typeAlias.TryGetValue(type, out string alias))
                return alias;

            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
                return $"{Nullable.GetUnderlyingType(type).GetSafetyTypeName()}?";

            if (type.IsGenericType)
            {
                string name = type.Name.Split('`')[0];
                IEnumerable<string> args = type.GetGenericArguments().Select(t => t.GetSafetyTypeName());
                return $"{name}<{string.Join(", ", args)}>";
            }

            if (type.IsArray)
                return $"{type.GetElementType().GetSafetyTypeName()}[]";

            if (type.IsProxyableConstructors() || type.IsInterfaceProxyable())
                return type.GetProxyName();

            return type.IsNested ? $"{type.DeclaringType.GetSafetyTypeName()}.{type.Name}" : type.Name;
        }
        private static string GetProxyName(this Type type) => $"{type.Name}Proxy";
        private static string GetProxyAssetMenu(Type type) => $"CreateAssetMenu(fileName = \"{type.GetProxyName()}\", menuName = \"Proxy/{type.Name}\")";
        private static void SaveProxy(StringBuilder stringBuilder, Type classProxy)
        {
            string dir = Path.Combine(Application.dataPath, "ProxyGenerated");
            string path = Path.Combine(dir, $"{classProxy.GetProxyName()}.cs");

            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            string content = stringBuilder.ToString();

            if (File.Exists(path) && File.ReadAllText(path) == content)
                return;

            File.WriteAllText(path, content);
        }
        private static bool HasAttribute<TAttribute>(this MemberInfo element, out TAttribute attribute) where TAttribute : Attribute
        {
            attribute = element?.GetCustomAttribute<TAttribute>();
            return attribute != null;
        }
        private static bool IsProxyableConstructors(this Type type) => type.GetConstructors()
            .Any(c => c.HasAttribute(out GenerateProxy _) || 
            c.HasAttribute(out GenerateScriptableObjectProxy _));
        private static bool IsInterfaceProxyable(this Type type) => type.HasAttribute(out GenerateInterfaceProxy _);
        private static bool IsList(this Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>);
    }
}