namespace UnityIceFebruary.Proxy
{
    using IceFebruary.Proxy;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Text;
    using UnityEditor;
    using UnityEngine;

    public static class ProxyGenerator
    {
        private const string AutoGeneratedWarning = "// AUTO-GENERATED. DO NOT EDIT.";

        [MenuItem("Tools/Generate all proxies")]
        public static void Generate()
        {
            List<Type> allTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(assembly => assembly.GetTypes())
                .ToList();

            IEnumerable<Type> interfaceProxies = allTypes.Where(type => type.IsInterfaceProxyable());
            IEnumerable<Type> classProxies = allTypes.Where(type => type.IsProxyableConstructors());

            foreach (Type type in interfaceProxies)
                GenerateInterfaceProxy(type);
            foreach (Type type in classProxies)
                GenerateClassProxy(type);

            AssetDatabase.Refresh();

            Debug.Log("Proxy Generation Complete!");
        }
        private static void GenerateClassProxy(Type classProxy)
        {
            StringBuilder stringBuilder = new();
            GenerateProxy attribute = null;

            ConstructorInfo constructor = classProxy.GetConstructors()
                .FirstOrDefault(c => c.HasAttribute(out attribute));

            if (constructor == null)
                return;

            ParameterInfo[] parameters = constructor.GetParameters();
            Type interfaceType = attribute?.InterfaceType;

            string proxyName = classProxy.GetProxyName();
            string inheritance = interfaceType != null ? $" : {interfaceType.GetProxyName()}" : string.Empty;

            stringBuilder.AppendLine(AutoGeneratedWarning);

            SetUsings(stringBuilder, parameters);

            stringBuilder.AppendLine("[Serializable]");
            stringBuilder.AppendLine($"public class {proxyName}{inheritance}");
            stringBuilder.AppendLine("{");

            foreach (ParameterInfo parameter in parameters)
            {
                Type parameterType = parameter.ParameterType;
                string typeName = parameterType.GetSafetyTypeName();

                bool isPolymorphic = parameterType.IsInterface || parameterType.IsAbstract;
                string stringAttribute = isPolymorphic ? "[SerializeReference, InterfaceImplementation]" : "[SerializeField]";

                stringBuilder.AppendLine($"    {stringAttribute} private {typeName} _{parameter.Name};");
            }

            stringBuilder.AppendLine();

            SetConstructor(stringBuilder, interfaceType, classProxy, parameters);

            stringBuilder.AppendLine("}");

            SaveProxy(proxyName, stringBuilder);
        }
        private static void GenerateInterfaceProxy(Type interfaceProxy)
        {
            string proxyName = interfaceProxy.GetProxyName();
            StringBuilder sb = new();

            sb.AppendLine(AutoGeneratedWarning);
            sb.AppendLine($"public interface {proxyName}");
            sb.AppendLine("{");
            sb.AppendLine($"    {interfaceProxy.Name} ToPoco();");
            sb.AppendLine("}");

            SaveProxy(proxyName, sb);
        }
        private static void SetUsings(StringBuilder sb, ParameterInfo[] parameters)
        {
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using System;");

            if (parameters.Any(p => p.ParameterType.IsGenericType))
                sb.AppendLine("using System.Collections.Generic;");

            if (parameters.Any(p => p.ParameterType.IsArray || p.ParameterType.IsList()))
                sb.AppendLine("using System.Linq;");

            sb.AppendLine();
        }
        private static void SetConstructor(StringBuilder sb, Type interfaceType, Type classProxy, ParameterInfo[] parameters)
        {
            string returnType = interfaceType != null ? interfaceType.Name : classProxy.Name;

            sb.Append($"    public {returnType} ToPoco() => new {classProxy.Name}(");

            IEnumerable<string> values = parameters.Select(parameter => {
                Type type = parameter.ParameterType;
                string parameterName = parameter.Name;
                if (type.IsProxyableConstructors() || type.IsInterfaceProxyable())
                    return $"_{parameter.Name}.ToPoco()";
                if (type.IsList() && type.GetGenericArguments()[0].IsProxyableConstructors())
                    return $"_{parameter.Name}.Select(x => x.ToPoco()).ToList()";
                if (type.IsArray && type.GetElementType().IsProxyableConstructors())
                    return $"_{parameter.Name}.Select(x => x.ToPoco()).ToArray()";
                return $"_{parameter.Name}";
            });

            sb.Append(string.Join(", ", values));
            sb.AppendLine(");");
        }
        private static void SaveProxy(string proxyName, StringBuilder sb)
        {
            string dir = Path.Combine(Application.dataPath, "ProxyGenerated");
            string path = Path.Combine(dir, $"{proxyName}.cs");

            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            string content = sb.ToString();

            if (File.Exists(path) && File.ReadAllText(path) == content)
                return;

            File.WriteAllText(path, content);
        }
        private static string GetSafetyTypeName(this Type type)
        {
            if (_typeAlias.TryGetValue(type, out string alias))
                return alias;

            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
                return $"{Nullable.GetUnderlyingType(type).GetSafetyTypeName()}?";

            if (type.IsGenericType)
            {
                string name = type.Name.Split('`')[0];
                IEnumerable<string> args = type.GetGenericArguments().Select(t => t.GetSafetyTypeName());
                return $"{name}<{string.Join(", ", args)}>";
            }

            if (type.IsArray)
                return $"{type.GetElementType().GetSafetyTypeName()}[]";

            if (type.IsProxyableConstructors() || type.IsInterfaceProxyable())
                return type.GetProxyName();

            return type.IsNested ? $"{type.DeclaringType.GetSafetyTypeName()}.{type.Name}" : type.Name;
        }
        private static readonly Dictionary<Type, string> _typeAlias = new()
        {
            { typeof(bool), "bool" },
            { typeof(byte), "byte" },
            { typeof(char), "char" },
            { typeof(decimal), "decimal" },
            { typeof(double), "double" },
            { typeof(float), "float" },
            { typeof(int), "int" },
            { typeof(long), "long" },
            { typeof(sbyte), "sbyte" },
            { typeof(short), "short" },
            { typeof(string), "string" },
            { typeof(uint), "uint" },
            { typeof(ulong), "ulong" },
            { typeof(ushort), "ushort" },
            { typeof(void), "void" }
        };
        private static string GetProxyName(this Type type) => $"{type.Name}Proxy";
        private static bool IsProxyableConstructors(this Type type) => type.GetConstructors().Any(c =>
        c.HasAttribute(out GenerateProxy _) || 
        c.HasAttribute(out GenerateInterfaceProxy _) ||
        c.HasAttribute(out GenerateScriptableObjectProxy _));
        private static bool IsInterfaceProxyable(this Type type) => type.IsInterface && type.HasAttribute(out GenerateInterfaceProxy _);
        private static bool IsList(this Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>);
        private static bool HasAttribute<TAttribute>(this MemberInfo element, out TAttribute attr) where TAttribute : Attribute
        {
            attr = element?.GetCustomAttribute<TAttribute>();
            return attr != null;
        }
    }
}