[System.Serializable]
public sealed class AnimatorBoolField_AUTOGENERATED
{
	[UnityEngine.SerializeField] private AnimatorFieldData_AUTOGENERATED _animatorFieldData;
	public IceFebruary.Animation.AnimatorBoolField ToPoco() => new IceFebruary.Animation.AnimatorBoolField(_animatorFieldData.ToPoco());
}
