//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class AnimatorFieldData_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IAnimator_AUTOGENERATED _animator;
    [UnityEngine.SerializeField] private System.Int32 _hash;
    public IceFebruary.Animation.AnimatorFieldData ToPoco() => new IceFebruary.Animation.AnimatorFieldData(_animator == null ? default : _animator.ToPoco(), _hash);
}
