[System.Serializable]
public sealed class AnimatorTrigger_AUTOGENERATED
{
    [UnityEngine.SerializeField] private AnimatorFieldData_AUTOGENERATED _animatorFieldData;
    public IceFebruary.Animation.AnimatorTrigger ToPoco() => new IceFebruary.Animation.AnimatorTrigger(_animatorFieldData == null ? default : _animatorFieldData.ToPoco());
}
