[System.Serializable]
public sealed class AnimatorIntField_AUTOGENERATED
{
	[UnityEngine.SerializeField] private AnimatorFieldData_AUTOGENERATED _animatorFieldData;
	public IceFebruary.Animation.AnimatorIntField ToPoco() => new IceFebruary.Animation.AnimatorIntField(_animatorFieldData.ToPoco());
}
