[System.Serializable]
public sealed class AnimatorFloatField_AUTOGENERATED
{
    [UnityEngine.SerializeField] private AnimatorFieldData_AUTOGENERATED _animatorFieldData;
    public IceFebruary.Animation.AnimatorFloatField ToPoco() => new IceFebruary.Animation.AnimatorFloatField(_animatorFieldData.ToPoco());
}
