[System.Serializable]
public sealed class AreaScannerConfig_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _position;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRotor2Provider_AUTOGENERATED _rotation;
    [UnityEngine.SerializeField] private AreaScannerSettings_AUTOGENERATED _settings;
    public AreaScannerConfig ToPoco() => new AreaScannerConfig(_position.ToPoco(), _rotation.ToPoco(), _settings.ToPoco());
}
