//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class AreaScannerConfig_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _position;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRotor2Provider_AUTOGENERATED _rotation;
    [UnityEngine.SerializeField] private AreaScannerSettings_AUTOGENERATED _settings;
    public AreaScannerConfig ToPoco() => new AreaScannerConfig(_position == null ? default : _position.ToPoco(), _rotation == null ? default : _rotation.ToPoco(), _settings == null ? default : _settings.ToPoco());
}
