[System.Serializable]
public sealed class Circle_AUTOGENERATED{
	[UnityEngine.SerializeField] private System.Single _radius;
	public IceFebruary.Shapes.Circle ToPoco() => new IceFebruary.Shapes.Circle(_radius);
}
