[System.Serializable]
public sealed class Circle_AUTOGENERATED : IShape_AUTOGENERATED
{
	[UnityEngine.SerializeField] private System.Single _radius;
	public IceFebruary.Shapes.IShape ToPoco() => new IceFebruary.Shapes.Circle(_radius);
}
