[System.Serializable]
public sealed class ContactFilter2D_AUTOGENERATED
{
	[UnityEngine.SerializeField] private LayerMask_AUTOGENERATED _layerMask;
	[UnityEngine.SerializeField] private System.Boolean _useTriggers;
	public IceFebruary.Physics.ContactFilter2D ToPoco() => new IceFebruary.Physics.ContactFilter2D(_layerMask.ToPoco(), _useTriggers);
}
