[System.Serializable]
public sealed class DirectionRotor2Provider_AUTOGENERATED : IRotor2Provider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _from;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _to;
	public IceFebruary.Space.Rotor2Provider.IRotor2Provider ToPoco() => new IceFebruary.Space.Rotor2Provider.DirectionRotor2Provider(_from.ToPoco(), _to.ToPoco());
}
