[System.Serializable]
public sealed class DirectionPointProvider_AUTOGENERATED : IPointProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPointProvider_AUTOGENERATED _from;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPointProvider_AUTOGENERATED _to;
	public IceFebruary.Space.PointProvider.IPointProvider ToPoco() => new IceFebruary.Space.PointProvider.DirectionPointProvider(_from.ToPoco(), _to.ToPoco());
}
