[System.Serializable]
public class DirectionAngleProvider_AUTOGENERATED : IAngleProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPointProvider_AUTOGENERATED _from;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPointProvider_AUTOGENERATED _to;
	public IceFebruary.Space.AngleProvider.IAngleProvider ToPoco() => new IceFebruary.Space.AngleProvider.DirectionAngleProvider(_from.ToPoco(), _to.ToPoco());
}
