[System.Serializable]
public sealed class GameAssemblerConfig_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ICamera_AUTOGENERATED _camera;
    [UnityEngine.SerializeField] private StickmanSpawnList_AUTOGENERATED _stickmanSpawnList;
    [UnityEngine.SerializeField] private GameAssemblerSettings_AUTOGENERATED _settings;
    public GameAssemblerConfig ToPoco() => new GameAssemblerConfig(_camera.ToPoco(), _stickmanSpawnList.ToPoco(), _settings.ToPoco());
}
