//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class GameAssemblerConfig_AUTOGENERATED
{
    [UnityEngine.SerializeField] private SpawnList_AUTOGENERATED _spawnList;
    [UnityEngine.SerializeField] private GameAssemblerSettings_AUTOGENERATED _settings;
    public GameAssemblerConfig ToPoco() => new GameAssemblerConfig(_spawnList == null ? default : _spawnList.ToPoco(), _settings == null ? default : _settings.ToPoco());
}
