[System.Serializable]
public sealed class GroundDetectionSettings_AUTOGENERATED{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _groundDetectorPosition;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRotor2Provider_AUTOGENERATED _groundDetectorRotation;
	[UnityEngine.SerializeField] private GroundCheckSettings_AUTOGENERATED _groundCheckSettings;
	public GroundDetectionSettings ToPoco() => new GroundDetectionSettings(_groundDetectorPosition.ToPoco(), _groundDetectorRotation.ToPoco(), _groundCheckSettings.ToPoco());
}
