[System.Serializable]
public sealed class HingeJoint2DComponent_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _gameObject;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IHingeJoint2D_AUTOGENERATED _hingeJoint2D;
    public HingeJoint2DComponent ToPoco() => new HingeJoint2DComponent(_gameObject.ToPoco(), _hingeJoint2D.ToPoco());
}
