//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class ItemSettings_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _gameObject;
    [UnityEngine.SerializeField] private Component_IHingeJoint2D_AUTOGENERATED[] _holders;
    [UnityEngine.SerializeField] private PhysicsBalancerConfig_AUTOGENERATED _physicsLimbConfig;
    public ItemSettings ToPoco() => new ItemSettings(_gameObject == null ? default : _gameObject.ToPoco(), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_holders ?? new Component_IHingeJoint2D_AUTOGENERATED[0], element => element.ToPoco())), _physicsLimbConfig == null ? default : _physicsLimbConfig.ToPoco());
}
