[System.Serializable]
public sealed class LayerMask_AUTOGENERATED{
	[UnityEngine.SerializeField] private System.Int32 _mask;
	public IceFebruary.Physics.LayerMask ToPoco() => new IceFebruary.Physics.LayerMask(_mask);
}
