//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class LerpVector2Provider_AUTOGENERATED : IVector2Provider_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _first;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _second;
    [UnityEngine.SerializeField] private System.Single _interpolation;
    public IceFebruary.Space.Vector2Provider.IVector2Provider ToPoco() => new IceFebruary.Space.Vector2Provider.LerpVector2Provider(_first == null ? default : _first.ToPoco(), _second == null ? default : _second.ToPoco(), _interpolation);
}
