//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class MovementConfig_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _pushBody;
    [UnityEngine.SerializeField] private MovementSettings_AUTOGENERATED _settings;
    [UnityEngine.SerializeField] private AreaScannerConfig_AUTOGENERATED _groundAreaScannerConfig;
    public MovementConfig ToPoco() => new MovementConfig(_pushBody == null ? default : _pushBody.ToPoco(), _settings == null ? default : _settings.ToPoco(), _groundAreaScannerConfig == null ? default : _groundAreaScannerConfig.ToPoco());
}
