[System.Serializable]
public sealed class MovementSettings_AUTOGENERATED{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _pushBody;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPhysicsBalancer _leftHip;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPhysicsBalancer _rightHip;
	[UnityEngine.SerializeField] private IPhysicsBalancer[] _shins;
	[UnityEngine.SerializeField] private MovementStatistick_AUTOGENERATED _movementStatisticks;
	public MovementSettings ToPoco() => new MovementSettings(_pushBody.ToPoco(), _leftHip, _rightHip, _shins, _movementStatisticks.ToPoco());
}
