[System.Serializable]
public sealed class MovementConfig_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _pushBody;
	[UnityEngine.SerializeField] private MovementSettings_AUTOGENERATED _settings;
	[UnityEngine.SerializeField] private AreaScannerConfig_AUTOGENERATED _groundAreaScannerConfig;
	public MovementConfig ToPoco() => new MovementConfig(_pushBody.ToPoco(), _settings.ToPoco(), _groundAreaScannerConfig.ToPoco());
}
