[System.Serializable]
public sealed class MovementSettings_AUTOGENERATED{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _pushBody;
	[UnityEngine.SerializeField] private AnimatorFloatField_AUTOGENERATED _movementFloat;
	[UnityEngine.SerializeField] private MovementStatistick_AUTOGENERATED _movementStatisticks;
	public MovementSettings ToPoco() => new MovementSettings(_pushBody.ToPoco(), _movementFloat.ToPoco(), _movementStatisticks.ToPoco());
}
