[System.Serializable]
public sealed class NormalizedVector2Provider_AUTOGENERATED : IVector2Provider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _vector2;
	public IceFebruary.Space.Vector2Provider.IVector2Provider ToPoco() => new IceFebruary.Space.Vector2Provider.NormalizedVector2Provider(_vector2.ToPoco());
}
