[System.Serializable]
public class PhysicsLimbSettings_AUTOGENERATED{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _rigidbody2D;
	[UnityEngine.SerializeField] private PhysicsBalancerSettings_AUTOGENERATED _balancerSettings;
	public PhysicsLimbSettings ToPoco() => new PhysicsLimbSettings(_rigidbody2D.ToPoco(), _balancerSettings.ToPoco());
}
