[System.Serializable]
public class PhysicsLimbSettings_AUTOGENERATED{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IceFebruary.Physics.IRigidbody2D _rigidbody2D;
	[UnityEngine.SerializeField] private PhysicsBalancerSettings_AUTOGENERATED _balancerSettings;
	public PhysicsLimbSettings ToPoco() => new PhysicsLimbSettings(_rigidbody2D, _balancerSettings.ToPoco());
}
