[System.Serializable]
public sealed class PhysicsBalancerConfig_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _rigidbody2D;
    [UnityEngine.SerializeField] private PhysicsBalancerSettings_AUTOGENERATED _settings;
    public PhysicsBalancerConfig ToPoco() => new PhysicsBalancerConfig(_rigidbody2D == null ? default : _rigidbody2D.ToPoco(), _settings == null ? default : _settings.ToPoco());
}
