[System.Serializable]
public sealed class PhysicsLimbConfig_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _rigidbody2D;
	[UnityEngine.SerializeField] private PhysicsBalancerSettings_AUTOGENERATED _settings;
	public PhysicsLimbConfig ToPoco() => new PhysicsLimbConfig(_rigidbody2D.ToPoco(), _settings.ToPoco());
}
