[System.Serializable]
public sealed class PickUpSettings_AUTOGENERATED{
	[UnityEngine.SerializeField] private IRigidbody2D_AUTOGENERATED[] _rigidbodies;
	[UnityEngine.SerializeField] private IGameObject_AUTOGENERATED[] _gameObjects;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _playerPosition;
	[UnityEngine.SerializeField] private PickUpStatisticks_AUTOGENERATED _pickUpStatisticks;
	public PickUpSettings ToPoco() => new PickUpSettings(System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_rigidbodies ?? new IRigidbody2D_AUTOGENERATED[0], element => element.ToPoco())), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_gameObjects ?? new IGameObject_AUTOGENERATED[0], element => element.ToPoco())), _playerPosition.ToPoco(), _pickUpStatisticks.ToPoco());
}
