[System.Serializable]
public sealed class PickUpConfig_AUTOGENERATED
{
    [UnityEngine.SerializeField] private Rigidbody2DComponent_AUTOGENERATED[] _entityHands;
    [UnityEngine.SerializeField] private PickUpSettings_AUTOGENERATED _settings;
    [UnityEngine.SerializeField] private AreaScannerSettings_AUTOGENERATED _itemAreaScannerSettings;
    public PickUpConfig ToPoco() => new PickUpConfig(System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_entityHands ?? new Rigidbody2DComponent_AUTOGENERATED[0], element => element.ToPoco())), _settings == null ? default : _settings.ToPoco(), _itemAreaScannerSettings == null ? default : _itemAreaScannerSettings.ToPoco());
}
