[System.Serializable]
public class RagdollScema_AUTOGENERATED{
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _head;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _body;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _shoulder1;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _forearm1;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _hand1;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _shoulder2;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _forearm2;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _hand2;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _hip1;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _shin1;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _foot1;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _hip2;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _shin2;
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED _foot2;
	public RagdollScema ToPoco() => new RagdollScema(_head.ToPoco(), _body.ToPoco(), _shoulder1.ToPoco(), _forearm1.ToPoco(), _hand1.ToPoco(), _shoulder2.ToPoco(), _forearm2.ToPoco(), _hand2.ToPoco(), _hip1.ToPoco(), _shin1.ToPoco(), _foot1.ToPoco(), _hip2.ToPoco(), _shin2.ToPoco(), _foot2.ToPoco());
}
