[System.Serializable]
public sealed class RagdollConfig_AUTOGENERATED
{
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _head;
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _body;
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _hip1;
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _shin1;
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _foot1;
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _hip2;
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _shin2;
    [UnityEngine.SerializeField] private PhysicsLimbConfig_AUTOGENERATED _foot2;
    public RagdollConfig ToPoco() => new RagdollConfig(_head.ToPoco(), _body.ToPoco(), _hip1.ToPoco(), _shin1.ToPoco(), _foot1.ToPoco(), _hip2.ToPoco(), _shin2.ToPoco(), _foot2.ToPoco());
}
