[System.Serializable]
public sealed class RagdollSchema_AUTOGENERATED{
	[UnityEngine.SerializeField] private PhysicsLimbSettings_AUTOGENERATED[] _physicsLimbSettings;
	public RagdollSchema ToPoco() => new RagdollSchema(System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_physicsLimbSettings ?? new PhysicsLimbSettings_AUTOGENERATED[0], element => element.ToPoco())));
}
