[System.Serializable]
public sealed class Rectangle_AUTOGENERATED : IShape_AUTOGENERATED
{
    [UnityEngine.SerializeField] private Vector2_AUTOGENERATED _size;
    public IceFebruary.Shapes.IShape ToPoco() => new IceFebruary.Shapes.Rectangle(_size.ToPoco());
}
