[System.Serializable]
public sealed class Rectangle_AUTOGENERATED{
	[UnityEngine.SerializeField] private IceFebruary.Space.Vector2 _size;
	public IceFebruary.Shapes.Rectangle ToPoco() => new IceFebruary.Shapes.Rectangle(_size);
}
