[System.Serializable]
public sealed class Rigidbody2DComponent_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _gameObject;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _rigidbody2D;
    public Rigidbody2DComponent ToPoco() => new Rigidbody2DComponent(_gameObject.ToPoco(), _rigidbody2D.ToPoco());
}
