[System.Serializable]
public sealed class Rotor2_AUTOGENERATED
{
    [UnityEngine.SerializeField] private System.Single _scalar;
    [UnityEngine.SerializeField] private System.Single _xy;
    public IceFebruary.Space.Rotor2 ToPoco() => new IceFebruary.Space.Rotor2(_scalar, _xy);
}
