[System.Serializable]
public sealed class Rotor2Provider_AUTOGENERATED : IRotor2Provider_AUTOGENERATED
{
	[UnityEngine.SerializeField] private IceFebruary.Space.Rotor2 _rotor2;
	public IceFebruary.Space.Rotor2Provider.IRotor2Provider ToPoco() => new IceFebruary.Space.Rotor2Provider.Rotor2Provider(_rotor2);
}
