[System.Serializable]
public class Rotor2AngleProvider_AUTOGENERATED : IAngleProvider_AUTOGENERATED
{
	[UnityEngine.SerializeField] private IceFebruary.Space.Rotor2 _rotor2;
	public IceFebruary.Space.AngleProvider.IAngleProvider ToPoco() => new IceFebruary.Space.AngleProvider.Rotor2AngleProvider(_rotor2);
}
