[System.Serializable]
public sealed class ScaleVector2Provider_AUTOGENERATED : IVector2Provider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _pointProvider;
	[UnityEngine.SerializeField] private System.Single _scale;
	public IceFebruary.Space.Vector2Provider.IVector2Provider ToPoco() => new IceFebruary.Space.Vector2Provider.ScaleVector2Provider(_pointProvider.ToPoco(), _scale);
}
