[System.Serializable]
public class ScalePointProvider_AUTOGENERATED : IPointProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPointProvider_AUTOGENERATED _pointProvider;
	[UnityEngine.SerializeField] private System.Single _scale;
	public IceFebruary.Space.PointProvider.IPointProvider ToPoco() => new IceFebruary.Space.PointProvider.ScalePointProvider(_pointProvider.ToPoco(), _scale);
}
