[System.Serializable]
public sealed class ScreenToWorldVector2Provider_AUTOGENERATED : IVector2Provider_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _inputProvider;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ICamera_AUTOGENERATED _camera;
    public IceFebruary.Space.Vector2Provider.IVector2Provider ToPoco() => new IceFebruary.Space.Vector2Provider.ScreenToWorldVector2Provider(_inputProvider.ToPoco(), _camera.ToPoco());
}
