[System.Serializable]
public sealed class SpacePointProvider_AUTOGENERATED : IPointProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IPointProvider_AUTOGENERATED _pointProvider;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform2D_AUTOGENERATED _space;
	public IceFebruary.Space.PointProvider.IPointProvider ToPoco() => new IceFebruary.Space.PointProvider.SpacePointProvider(_pointProvider.ToPoco(), _space.ToPoco());
}
