[System.Serializable]
public sealed class SpaceVector2Provider_AUTOGENERATED : IVector2Provider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _vector2;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _space;
	public IceFebruary.Space.Vector2Provider.IVector2Provider ToPoco() => new IceFebruary.Space.Vector2Provider.SpaceVector2Provider(_vector2.ToPoco(), _space.ToPoco());
}
