[System.Serializable]
public sealed class SpaceRotor2Provider_AUTOGENERATED : IRotor2Provider_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRotor2Provider_AUTOGENERATED _angleProvider;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _space;
    public IceFebruary.Space.Rotor2Provider.IRotor2Provider ToPoco() => new IceFebruary.Space.Rotor2Provider.SpaceRotor2Provider(_angleProvider == null ? default : _angleProvider.ToPoco(), _space == null ? default : _space.ToPoco());
}
