[System.Serializable]
public sealed class SpaceAngleProvider_AUTOGENERATED : IAngleProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IAngleProvider_AUTOGENERATED _angleProvider;
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _space;
	public IceFebruary.Space.AngleProvider.IAngleProvider ToPoco() => new IceFebruary.Space.AngleProvider.SpaceAngleProvider(_angleProvider.ToPoco(), _space.ToPoco());
}
