[System.Serializable]
public sealed class SpawnSettings_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _gameObject;
    [UnityEngine.SerializeField] private Vector2_AUTOGENERATED _position;
    public SpawnSettings ToPoco() => new SpawnSettings(_gameObject == null ? default : _gameObject.ToPoco(), _position == null ? default : _position.ToPoco());
}
