[System.Serializable]
public sealed class SpawnSettings_AUTOGENERATED{
	[UnityEngine.SerializeField] private Vector2_AUTOGENERATED _position;
	public SpawnSettings ToPoco() => new SpawnSettings(_position.ToPoco());
}
