[System.Serializable]
public sealed class StickmanSpawnSettings_AUTOGENERATED
{
    [UnityEngine.SerializeField] private Vector2_AUTOGENERATED _position;
    public StickmanSpawnSettings ToPoco() => new StickmanSpawnSettings(_position == null ? default : _position.ToPoco());
}
