[System.Serializable]
public sealed class SumVector2Provider_AUTOGENERATED : IVector2Provider_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _minuend;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _subtrahend;
    public IceFebruary.Space.Vector2Provider.IVector2Provider ToPoco() => new IceFebruary.Space.Vector2Provider.SumVector2Provider(_minuend.ToPoco(), _subtrahend.ToPoco());
}
