[System.Serializable]
public sealed class TransformAngleProvider_AUTOGENERATED : IAngleProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _transform;
	public IceFebruary.Space.AngleProvider.IAngleProvider ToPoco() => new IceFebruary.Space.AngleProvider.TransformAngleProvider(_transform.ToPoco());
}
