[System.Serializable]
public class TransformAngleProvider_AUTOGENERATED : IAngleProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IceFebruary.ITransform2D _transform;
	public IceFebruary.Space.AngleProvider.IAngleProvider ToPoco() => new IceFebruary.Space.AngleProvider.TransformAngleProvider(_transform);
}
