[System.Serializable]
public class TransformPointProvider_AUTOGENERATED : IPointProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IceFebruary.ITransform2D _transform;
	public IceFebruary.Space.PointProvider.IPointProvider ToPoco() => new IceFebruary.Space.PointProvider.TransformPointProvider(_transform);
}
