[System.Serializable]
public sealed class TransformPointProvider_AUTOGENERATED : IPointProvider_AUTOGENERATED
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _transform;
	public IceFebruary.Space.PointProvider.IPointProvider ToPoco() => new IceFebruary.Space.PointProvider.TransformPointProvider(_transform.ToPoco());
}
