//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class TransformRotor2Provider_AUTOGENERATED : IRotor2Provider_AUTOGENERATED
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _transform;
    public IceFebruary.Space.Rotor2Provider.IRotor2Provider ToPoco() => new IceFebruary.Space.Rotor2Provider.TransformRotor2Provider(_transform == null ? default : _transform.ToPoco());
}
