[System.Serializable]
public sealed class UnityHingeJoint2D_AUTOGENERATED : IHingeJoint2D_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.HingeJoint2D _unityObject;
    public IceFebruary.Physics.IHingeJoint2D ToPoco() => (IceFebruary.Physics.IHingeJoint2D)UnityIceFebruary.UnityMethods.Upsert(_unityObject);
}
