[System.Serializable]
public sealed class UnityAnimator_AUTOGENERATED : IAnimator_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Animator _unityObject;
    public IceFebruary.Animation.IAnimator ToPoco() => (IceFebruary.Animation.IAnimator)UnityIceFebruary.UnityMethods.Upsert(_unityObject);
}
