//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class UnityTransform_AUTOGENERATED : ITransform_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Transform _unityObject;
    public IceFebruary.ITransform ToPoco() => UnityIceFebruary.UnityMethods.Upsert<UnityEngine.Transform, IceFebruary.ITransform>(_unityObject);
}
