[System.Serializable]
public sealed class UnityAnimator_AUTOGENERATED : IAnimator_AUTOGENERATED
{
	[UnityEngine.SerializeField] private UnityEngine.Animator _animator;
	public IceFebruary.Animation.IAnimator ToPoco() => new UnityIceFebruary.Components.UnityAnimator(_animator);
}
