//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class UnityRigidbody2D_AUTOGENERATED : IRigidbody2D_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Rigidbody2D _unityObject;
    public IceFebruary.Physics.IRigidbody2D ToPoco() => UnityIceFebruary.UnityMethods.Upsert<UnityEngine.Rigidbody2D, IceFebruary.Physics.IRigidbody2D>(_unityObject);
}
