//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class UnityAnimator_AUTOGENERATED : IAnimator_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Animator _unityObject;
    public IceFebruary.Animation.IAnimator ToPoco() => UnityIceFebruary.UnityMethods.Upsert<UnityEngine.Animator, IceFebruary.Animation.IAnimator>(_unityObject);
}
