[System.Serializable]
public sealed class UnityRigidbody2D_AUTOGENERATED : IRigidbody2D_AUTOGENERATED
{
	[UnityEngine.SerializeField] private UnityEngine.Rigidbody2D _rigidbody2D;
	public IceFebruary.Physics.IRigidbody2D ToPoco() => new UnityIceFebruary.Components.UnityRigidbody2D(_rigidbody2D);
}
