[System.Serializable]
public sealed class UnityCamera_AUTOGENERATED : ICamera_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Camera _unityObject;
    public IceFebruary.Render.ICamera ToPoco() => (IceFebruary.Render.ICamera)UnityIceFebruary.UnityMethods.Upsert(_unityObject);
}
