[System.Serializable]
public sealed class UnityGameObject_AUTOGENERATED : IGameObject_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.GameObject _gameObject;
    public IceFebruary.IGameObject ToPoco() => new UnityIceFebruary.UnityGameObject(_gameObject);
}
