[System.Serializable]
public sealed class UnityGameObject_AUTOGENERATED : IGameObject_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.GameObject _unityObject;
    public IceFebruary.IGameObject ToPoco() => (IceFebruary.IGameObject)UnityIceFebruary.UnityMethods.Upsert(_unityObject);
}
