//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class UnityCollider2D_AUTOGENERATED : ICollider2D_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Collider2D _unityObject;
    public IceFebruary.Physics.ICollider2D ToPoco() => UnityIceFebruary.UnityMethods.Upsert<UnityEngine.Collider2D, IceFebruary.Physics.ICollider2D>(_unityObject);
}
