[System.Serializable]
public sealed class UnityRigidbody2D_AUTOGENERATED : IRigidbody2D_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Rigidbody2D _unityObject;
    public IceFebruary.Physics.IRigidbody2D ToPoco() => (IceFebruary.Physics.IRigidbody2D)UnityIceFebruary.UnityMethods.Upsert(_unityObject);
}
