[System.Serializable]
public sealed class UnityCollider2D_AUTOGENERATED : ICollider2D_AUTOGENERATED
{
	[UnityEngine.SerializeField] private UnityEngine.Collider2D _collider2D;
	public IceFebruary.Physics.ICollider2D ToPoco() => new UnityIceFebruary.Components.UnityCollider2D(_collider2D);
}
