//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class UnityHingeJoint2D_AUTOGENERATED : IHingeJoint2D_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.HingeJoint2D _unityObject;
    public IceFebruary.Physics.IHingeJoint2D ToPoco() => UnityIceFebruary.UnityMethods.Upsert<UnityEngine.HingeJoint2D, IceFebruary.Physics.IHingeJoint2D>(_unityObject);
}
