[System.Serializable]
public sealed class UnityHingeJoint2D_AUTOGENERATED : IHingeJoint2D_AUTOGENERATED
{
	[UnityEngine.SerializeField] private UnityEngine.HingeJoint2D _hingeJoint2D;
	public IceFebruary.Physics.IHingeJoint2D ToPoco() => new UnityIceFebruary.Components.UnityHingeJoint2D(_hingeJoint2D);
}
