[System.Serializable]
public sealed class UnityCollider2D_AUTOGENERATED : ICollider2D_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Collider2D _unityObject;
    public IceFebruary.Physics.ICollider2D ToPoco() => (IceFebruary.Physics.ICollider2D)UnityIceFebruary.UnityMethods.Upsert(_unityObject);
}
