[System.Serializable]
public sealed class UnityCamera_AUTOGENERATED : ICamera_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Camera _camera;
    public IceFebruary.Render.ICamera ToPoco() => new UnityIceFebruary.Components.UnityCamera(_camera);
}
