[System.Serializable]
public sealed class UnityTransform_AUTOGENERATED : ITransform2D_AUTOGENERATED
{
	[UnityEngine.SerializeField] private UnityEngine.Transform _transform;
	public IceFebruary.ITransform2D ToPoco() => new UnityIceFebruary.Components.UnityTransform(_transform);
}
