[System.Serializable]
public sealed class UnityTransform_AUTOGENERATED : ITransform_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Transform _transform;
    public IceFebruary.ITransform ToPoco() => new UnityIceFebruary.Components.UnityTransform(_transform);
}
