[System.Serializable]
public sealed class UnityGameObject2D_AUTOGENERATED : IGameObject_AUTOGENERATED
{
	[UnityEngine.SerializeField] private UnityEngine.GameObject _gameObject;
	public IceFebruary.IGameObject ToPoco() => new UnityIceFebruary.UnityGameObject2D(_gameObject);
}
