//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class UnityGameObject_AUTOGENERATED : IGameObject_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.GameObject _unityObject;
    public IceFebruary.IGameObject ToPoco() => UnityIceFebruary.UnityMethods.Upsert<UnityEngine.GameObject, IceFebruary.IGameObject>(_unityObject);
}
