//AUTOGENERATED. DO NOT EDIT.
[System.Serializable]
public sealed class UnityCamera_AUTOGENERATED : ICamera_AUTOGENERATED
{
    [UnityEngine.SerializeField] private UnityEngine.Camera _unityObject;
    public IceFebruary.Render.ICamera ToPoco() => UnityIceFebruary.UnityMethods.Upsert<UnityEngine.Camera, IceFebruary.Render.ICamera>(_unityObject);
}
