[System.Serializable]
public sealed class Vector2_AUTOGENERATED{
	[UnityEngine.SerializeField] private System.Single _x;
	[UnityEngine.SerializeField] private System.Single _y;
	public IceFebruary.Space.Vector2 ToPoco() => new IceFebruary.Space.Vector2(_x, _y);
}
