[System.Serializable]
public sealed class Vector2PointProvider_AUTOGENERATED : IPointProvider_AUTOGENERATED
{
	[UnityEngine.SerializeField] private IceFebruary.Space.Vector2 _vector2;
	public IceFebruary.Space.PointProvider.IPointProvider ToPoco() => new IceFebruary.Space.PointProvider.Vector2PointProvider(_vector2);
}
