[System.Serializable]
public sealed class Vector2Provider_AUTOGENERATED : IVector2Provider_AUTOGENERATED
{
    [UnityEngine.SerializeField] private Vector2_AUTOGENERATED _vector2;
    public IceFebruary.Space.Vector2Provider.IVector2Provider ToPoco() => new IceFebruary.Space.Vector2Provider.Vector2Provider(_vector2.ToPoco());
}
