//AUTOGENERATED. DO NOT EDIT.
public sealed class BulletConfig_AUTOGENERATED : UnityIceFebruary.UnityInfo
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _gameObject;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _rigidbody2D;
    public override IceFebruary.IRootConfig ToPoco() => new BulletConfig(_gameObject == null ? default : _gameObject.ToPoco(), _rigidbody2D == null ? default : _rigidbody2D.ToPoco());
}
