//AUTOGENERATED. DO NOT EDIT.
public sealed class BulletConfig_AUTOGENERATED : UnityIceFebruary.UnityInfo
{
    [UnityEngine.SerializeField] private Component_IRigidbody2D_AUTOGENERATED _rigidbody2DComponent;
    public override IceFebruary.IRootConfig ToPoco() => new BulletConfig(_rigidbody2DComponent == null ? default : _rigidbody2DComponent.ToPoco());
}
