public sealed class CameraConfig_AUTOGENERATED : UnityIceFebruary.UnityInfo
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _transform;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ICamera_AUTOGENERATED _camera;
    [UnityEngine.SerializeField] private CameraSettings_AUTOGENERATED _settings;
    public override IceFebruary.IRootConfig ToPoco() => new CameraConfig(_transform == null ? default : _transform.ToPoco(), _camera == null ? default : _camera.ToPoco(), _settings == null ? default : _settings.ToPoco());
}
