public sealed class CameraConfig_AUTOGENERATED : UnityIceFebruary.UnityInfo
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ITransform_AUTOGENERATED _transform;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private ICamera_AUTOGENERATED _camera;
    [UnityEngine.SerializeField] private System.Single _interpolation;
    [UnityEngine.SerializeField] private System.Single _minSize;
    [UnityEngine.SerializeField] private System.Single _maxSize;
    public override IceFebruary.IRootConfig ToPoco() => new CameraConfig(_transform == null ? default : _transform.ToPoco(), _camera == null ? default : _camera.ToPoco(), _interpolation, _minSize, _maxSize);
}
