public sealed class ItemConfig_AUTOGENERATED : UnityIceFebruary.UnityInstantiateInfo<ItemConfig>
{
    [UnityEngine.SerializeField] private ItemSettings_AUTOGENERATED _settings;
    public override ItemConfig ToPoco() => new ItemConfig(_settings == null ? default : _settings.ToPoco());
}
