public sealed class ItemConfig_AUTOGENERATED : UnityIceFebruary.UnityInstantiateInfo<ItemConfig>
{
    [UnityEngine.SerializeField] private ItemSettings_AUTOGENERATED _itemSettings;
    public override ItemConfig ToPoco() => new ItemConfig(_itemSettings == null ? default : _itemSettings.ToPoco());
}
