public sealed class ItemConfig_AUTOGENERATED : UnityIceFebruary.UnityInstantiateInfo<ItemConfig>
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IGameObject_AUTOGENERATED _gameObject;
    [UnityEngine.SerializeField] private HingeJoint2DComponent_AUTOGENERATED[] _holders;
    [UnityEngine.SerializeField] private PhysicsBalancerConfig_AUTOGENERATED _physicsLimbConfig;
    public override ItemConfig ToPoco() => new ItemConfig(_gameObject == null ? default : _gameObject.ToPoco(), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(_holders ?? new HingeJoint2DComponent_AUTOGENERATED[0], element => element.ToPoco())), _physicsLimbConfig == null ? default : _physicsLimbConfig.ToPoco());
}
