//AUTOGENERATED. DO NOT EDIT.
public sealed class SawConfig_AUTOGENERATED : UnityIceFebruary.UnityInfo
{
    [UnityEngine.SerializeField] private ItemSettings_AUTOGENERATED _itemSettings;
    [UnityEngine.SerializeField] private AnimatorField_Boolean_AUTOGENERATED _animatorField;
    public override IceFebruary.IRootConfig ToPoco() => new SawConfig(_itemSettings == null ? default : _itemSettings.ToPoco(), _animatorField == null ? default : _animatorField.ToPoco());
}
