public sealed class SawConfig_AUTOGENERATED : UnityIceFebruary.UnityInstantiateInfo<SawConfig>
{
    [UnityEngine.SerializeField] private ItemSettings_AUTOGENERATED _itemSettings;
    [UnityEngine.SerializeField] private AnimatorBoolField_AUTOGENERATED _animatorField;
    public override SawConfig ToPoco() => new SawConfig(_itemSettings == null ? default : _itemSettings.ToPoco(), _animatorField == null ? default : _animatorField.ToPoco());
}
