public sealed class ShootingConfig_AUTOGENERATED : UnityIceFebruary.UnityInfo
{
    [UnityEngine.SerializeField] private ItemSettings_AUTOGENERATED _itemSettings;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _rigidbody2D;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _shootDirection;
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _shootPoint;
    [UnityEngine.SerializeField] private ShootingSettings_AUTOGENERATED _settings;
    public override IceFebruary.IRootConfig ToPoco() => new ShootingConfig(_itemSettings == null ? default : _itemSettings.ToPoco(), _rigidbody2D == null ? default : _rigidbody2D.ToPoco(), _shootDirection == null ? default : _shootDirection.ToPoco(), _shootPoint == null ? default : _shootPoint.ToPoco(), _settings == null ? default : _settings.ToPoco());
}
