public sealed class StickmanEntities_AUTOGENERATED : UnityIceFebruary.UnityInstantiateInfo<StickmanEntities>
{
	[UnityEngine.SerializeField] private RagdollSchema_AUTOGENERATED _balda;
	public override StickmanEntities ToPoco() => new StickmanEntities(_balda.ToPoco());
}
