public sealed class StickmanConfig_AUTOGENERATED : UnityIceFebruary.UnityInstantiateInfo<StickmanConfig>
{
    [UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IVector2Provider_AUTOGENERATED _stickmanPosition;
    [UnityEngine.SerializeField] private RagdollConfig_AUTOGENERATED _ragdollConfig;
    [UnityEngine.SerializeField] private MovementConfig_AUTOGENERATED _movementConfig;
    [UnityEngine.SerializeField] private PickUpConfig_AUTOGENERATED _pickUpConfig;
    public override StickmanConfig ToPoco() => new StickmanConfig(_stickmanPosition == null ? default : _stickmanPosition.ToPoco(), _ragdollConfig == null ? default : _ragdollConfig.ToPoco(), _movementConfig == null ? default : _movementConfig.ToPoco(), _pickUpConfig == null ? default : _pickUpConfig.ToPoco());
}
