public class StickmanEntities_AUTOGENERATED : UnityEngine.MonoBehaviour
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IRigidbody2D_AUTOGENERATED _balda;
	public StickmanEntities ToPoco() => new StickmanEntities(_balda.ToPoco());
}
