public sealed class StickmanConfig_AUTOGENERATED : UnityIceFebruary.UnityInstantiateInfo<StickmanConfig>
{
	[UnityEngine.SerializeField] private RagdollSchema_AUTOGENERATED _ragdollSchema;
	[UnityEngine.SerializeField] private GroundDetectionSettings_AUTOGENERATED _groundDetectionSettings;
	[UnityEngine.SerializeField] private MovementSettings_AUTOGENERATED _movementSettings;
	[UnityEngine.SerializeField] private PickUpSettings_AUTOGENERATED _pickUpSettings;
	public override StickmanConfig ToPoco() => new StickmanConfig(_ragdollSchema.ToPoco(), _groundDetectionSettings.ToPoco(), _movementSettings.ToPoco(), _pickUpSettings.ToPoco());
}
