public class StickmanEntities_AUTOGENERATED : UnityEngine.MonoBehaviour
{
	[UnityEngine.SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation] private IceFebruary.Physics.IRigidbody2D _balda;
	public StickmanEntities ToPoco() => new StickmanEntities(_balda);
}
