[System.Serializable]
public class UnityHingeJoint2D_AUTOGENERATED
{
	[UnityEngine.SerializeField] private UnityEngine.HingeJoint2D _component;
	public UnityEngine.HingeJoint2D ToPoco() => _component;
}
