//AUTOGENERATED. DO NOT EDIT.
[UnityEngine.CreateAssetMenu(fileName = "GameAssemblerSettings", menuName = "Proxy/GameAssemblerSettings")]
public sealed class GameAssemblerSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeField] private System.Int32 _startTimeCyclesBufferLength;
    [UnityEngine.SerializeField] private System.Int32 _startPhysicsCollidersBufferLength;
    public GameAssemblerSettings ToPoco() => new GameAssemblerSettings(_startTimeCyclesBufferLength, _startPhysicsCollidersBufferLength);
}
