//AUTOGENERATED. DO NOT EDIT.
[UnityEngine.CreateAssetMenu(fileName = "PickUpSettings", menuName = "Proxy/PickUpSettings")]
public sealed class PickUpSettings_AUTOGENERATED : UnityEngine.ScriptableObject
{
    [UnityEngine.SerializeField] private System.Single _maxSqrPickUpDistance;
    [UnityEngine.SerializeField] private System.Int32 _entityLayer;
    public PickUpSettings ToPoco() => new PickUpSettings(_maxSqrPickUpDistance, _entityLayer);
}
