using IceFebruary.Space.Vector2Provider;
using UnityEngine;
using UnityIceFebruary;

public class GameAssembler : MonoBehaviour
{
    [SerializeField] private GameAssemblerConfig_AUTOGENERATED _config;

    private UnityTime _time;
    private UnityPhysics2D _physics2D;
    private UnityObjectManager _objectManager;

    private UnityPlayerInputProvider _input;

    private void Awake()
    {
        GameAssemblerConfig gameAssemblerConfig = _config.ToPoco();
        GameAssemblerSettings gameAssemblerSettings = gameAssemblerConfig.Settings;

        _time = new(gameAssemblerSettings.StartTimeCyclesBufferLength);
        _physics2D = new(gameAssemblerSettings.StartPhysicsCollidersBufferLength);
        _objectManager = new();

        _input = new(new());

        _time.LaunchIFrame(_input);

        StickmanSpawnList stickmanSpawnList = gameAssemblerConfig.StickmanSpawnList;
        StickmanFactory stickmanFactory = new(_time, _physics2D, _objectManager);

        IVector2Provider playerCursor = new ScreenToWorldVector2Provider(
            new MouseVector2Provider(_input),
            gameAssemblerConfig.Camera);

        StickmanBuilder playerStickmanBuilder = stickmanFactory
            .Create(
            stickmanSpawnList.PlayerStickmanPrefab,
            stickmanSpawnList.PlayerSpawnsSetting.Position)
            .SetLimbs()
            .SetMovement()
            .SetItemHolder(playerCursor)
            .SetInput(_input);

        IVector2Provider playerStickmanPosition = playerStickmanBuilder.StickmanPosition;

        for (int index = 0; index < stickmanSpawnList.EnemiesSpawnSettings.Length; index++)
        {
            StickmanBuilder enemyStickmanBuilder = stickmanFactory.Create(
                stickmanSpawnList.EnemyStickmanPrefab,
                stickmanSpawnList.EnemiesSpawnSettings[index].Position);

            EnemyInputProvider enemyInput = new(
                enemyStickmanBuilder.StickmanPosition,
                playerStickmanPosition);

            IVector2Provider enemyCursor = new MouseVector2Provider(enemyInput);

            _time.LaunchIFrame(enemyInput);

            enemyStickmanBuilder
                .SetLimbs()
                .SetMovement()
                .SetItemHolder(enemyCursor)
                .SetInput(enemyInput);
        }
    }
    private void Update() => _time.DoFrame(Time.deltaTime);
    private void FixedUpdate() => _time.DoFixedFrame();
}
