using IceFebruary.Space.Vector2Provider;
using UnityEngine;
using UnityIceFebruary;

public sealed class GameAssembler : MonoBehaviour
{
    [SerializeField] private GameAssemblerConfig_AUTOGENERATED _config;

    private UnityTime _time;
    private UnityPhysics2D _physics2D;
    private UnityObjectManager _objectManager;

    private void Awake()
    {
        GameAssemblerConfig gameAssemblerConfig = _config.ToPoco();
        GameAssemblerSettings gameAssemblerSettings = gameAssemblerConfig.Settings;

        _time = new(gameAssemblerSettings.StartTimeCyclesBufferLength);
        _physics2D = new(gameAssemblerSettings.StartPhysicsCollidersBufferLength);
        _objectManager = new();

        UnityPlayerInputProvider playerInput = new(new());

        _time.LaunchIFrame(playerInput);

        IVector2Provider playerCursorPosition = new ScreenToWorldVector2Provider(
            new MouseVector2Provider(playerInput),
            gameAssemblerConfig.Camera);

        Factory<StickmanBuilder, StickmanConfig> stickmanFactory = new(_objectManager, () => new(_time, _physics2D));

        SpawnList spawnList = gameAssemblerConfig.StickmanSpawnList;
        SpawnSettings playerSpawnSettings = spawnList.PlayerSpawnsSetting;

        StickmanBuilder playerStickmanBuilder = stickmanFactory
            .Create(
            playerSpawnSettings.GameObject,
            playerSpawnSettings.Position)
            .SetLimbs()
            .SetMovement()
            .SetItemHolder(playerCursorPosition)
            .SetInput(playerInput);

        IVector2Provider playerStickmanPosition = playerStickmanBuilder.StickmanPosition;

        SpawnSettings[] enemiesSpawnList = spawnList.EnemiesSpawnSettings;

        for (int index = 0; index < enemiesSpawnList.Length; index++)
        {
            SpawnSettings enemySpawnSettings = enemiesSpawnList[index];

            StickmanBuilder enemyStickmanBuilder = stickmanFactory.Create(
                enemySpawnSettings.GameObject,
                enemySpawnSettings.Position);

            EnemyInputProvider enemyInput = new(
                enemyStickmanBuilder.StickmanPosition,
                playerStickmanPosition);

            _time.LaunchIFrame(enemyInput);

            IVector2Provider enemyCursorProvider = new MouseVector2Provider(enemyInput);

            enemyStickmanBuilder
                .SetLimbs()
                .SetMovement()
                .SetItemHolder(enemyCursorProvider)
                .SetInput(enemyInput);
        }

        Factory<ItemBuilder, ItemConfig> itemFactory = new(_objectManager, () => new(_time));

        SpawnSettings[] itemsSpawnList = spawnList.ItemsSpawnList;

        for (int index = 0; index < itemsSpawnList.Length; index++)
        {
            SpawnSettings itemSpawnSettings = itemsSpawnList[index];

            itemFactory.Create(
                itemSpawnSettings.GameObject,
                itemSpawnSettings.Position);
        }
    }
    private void Update() => _time.DoFrame(Time.deltaTime);
    private void FixedUpdate() => _time.DoFixedFrame();
}
