using IceFebruary.Space.Vector2Provider;
using UnityEngine;
using UnityIceFebruary;
using UnityIceFebruary.InterfaceImplementation;

public sealed class GameAssembler : MonoBehaviour
{
    [SerializeField] private GameAssemblerConfig_AUTOGENERATED _config;
    [SerializeReference, InterfaceImplementation] private IGameObject_AUTOGENERATED _weapon;

    private UnityTime _time;
    private UnityPhysics2D _physics2D;
    private UnityObjectManager _objectManager;

    private void Awake()
    {
        GameAssemblerConfig gameAssemblerConfig = _config.ToPoco();
        GameAssemblerSettings gameAssemblerSettings = gameAssemblerConfig.Settings;

        _time = new(gameAssemblerSettings.StartTimeCyclesBufferLength);
        _physics2D = new(gameAssemblerSettings.StartPhysicsCollidersBufferLength);
        _objectManager = new();

        UnityPlayerInputProvider playerInput = new(new());

        _time.LaunchIFrame(playerInput);

        IVector2Provider playerCursorPosition = new ScreenToWorldVector2Provider(
            new MouseVector2Provider(playerInput),
            gameAssemblerConfig.Camera);

        StickmanSpawnList stickmanSpawnList = gameAssemblerConfig.StickmanSpawnList;
        StickmanFactory stickmanFactory = new(_time, _physics2D, _objectManager);

        StickmanBuilder playerStickmanBuilder = stickmanFactory
            .Create(
            stickmanSpawnList.PlayerStickmanPrefab,
            stickmanSpawnList.PlayerSpawnsSetting.Position)
            .SetLimbs()
            .SetMovement()
            .SetItemHolder(playerCursorPosition)
            .SetInput(playerInput);

        IVector2Provider playerStickmanPosition = playerStickmanBuilder.StickmanPosition;

        for (int index = 0; index < stickmanSpawnList.EnemiesSpawnSettings.Length; index++)
        {
            StickmanBuilder enemyStickmanBuilder = stickmanFactory.Create(
                stickmanSpawnList.EnemyStickmanPrefab,
                stickmanSpawnList.EnemiesSpawnSettings[index].Position);

            EnemyInputProvider enemyInput = new(
                enemyStickmanBuilder.StickmanPosition,
                playerStickmanPosition);

            _time.LaunchIFrame(enemyInput);

            IVector2Provider enemyCursorProvider = new MouseVector2Provider(enemyInput);

            enemyStickmanBuilder
                .SetLimbs()
                .SetMovement()
                .SetItemHolder(enemyCursorProvider)
                .SetInput(enemyInput);
        }

        ItemFactory itemFactory = new(_weapon.ToPoco(), _objectManager);
        itemFactory.Create();
    }
    private void Update() => _time.DoFrame(Time.deltaTime);
    private void FixedUpdate() => _time.DoFixedFrame();
}
