namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using IceFebruary.Proxy;
    using System;
    using System.Linq;
    using System.Reflection;

    public static class ProxyTypeExtensions
    {
        private static readonly BindingFlags _flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;
        public static string GetProxyName(this Type type) => $"{type.Name}_{ProxyGenerator.AutogeneratedMark}";
        public static T GetAttribute<T>(this Type type) where T : GeneratorAttribute
        {
            T attributeOnType = type.GetCustomAttributes<T>(true).FirstOrDefault();

            if (attributeOnType != null)
                return attributeOnType;

            return type
                .GetMembers(_flags)
                .Select(member => member.GetCustomAttributes<T>(true).FirstOrDefault())
                .FirstOrDefault(attribute => attribute != null);
        }
        public static bool HasAttribute<T>(this Type type) where T : GeneratorAttribute
        {
            if (type.IsDefined(typeof(T), true))
                return true;

            return type
                .GetMembers(_flags)
                .Any(member => member.IsDefined(typeof(T), true));
        }
        public static bool IsProxyable(this Type type) => type.HasAttribute<GeneratorAttribute>();
        public static bool IsProxyableArray(this Type type, out Type elementType)
        {
            elementType = type.GetElementType();
            return type.IsArray && elementType.IsProxyable();
        }
        public static bool IsUnityBaseEntity(this Type type, out Type unityType)
        {
            unityType = type.BaseType;
            bool isUnityBaseEntity = unityType != null && unityType.IsGenericType && unityType.GetGenericTypeDefinition() == typeof(UnityBaseEntity<>);
            unityType = isUnityBaseEntity ? unityType.GetGenericArguments()[0] : null;
            return isUnityBaseEntity;
        }
    }
}
