namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using UnityEditor;
    using System.Linq;
    using System.IO;
    using System;
    using System.Reflection;
    using IceFebruary.Proxy;
    using UnityIceFebruary.HelpTools.Debuggers;

    public static class ProxyGenerator
    {
        public const string AutogeneratedMark = "AUTOGENERATED";
        public const string TroubleMark = "TROUBLES";

        [MenuItem("Tools/Generate scripts")]
        public static void Generate()
        {
            ProxyDirectory.RecoveryDirectories();

            Type[] inGameTypes = Assembly.Load("Assembly-CSharp").GetTypes()
                .Where(type => !type.Name.EndsWith(AutogeneratedMark))
                .ToArray();

            Type[] proxyableTypes = inGameTypes
                .Where(type => type.IsProxyable())
                .OrderBy(type => GetPriority(type))
                .ToArray();

            if (proxyableTypes.Length == 0)
            {
                ProxyGeneratorDebugger.WarnAboutProxyableAbsence();
                return;
            }

            ProxyGeneratorDebugger.DebugInformationAboutProxyableTypes(proxyableTypes);

            foreach (Type type in proxyableTypes)
            {
                GeneratorAttribute generatorAttribute = type.GetAttribute<GeneratorAttribute>();

                (Type attributeType, string code) = generatorAttribute switch
                {
                    Proxy => (typeof(Proxy), ProxyCodeBuilder.GetProxyCode(type)),
                    FieldProxy fieldProxy => (typeof(FieldProxy), ProxyCodeBuilder.GetFieldProxyCode(type, fieldProxy)),
                    InterfaceProxy => (typeof(InterfaceProxy), ProxyCodeBuilder.GetInterfaceProxyCode(type)),
                    ScriptableObjectProxy => (typeof(ScriptableObjectProxy), ProxyCodeBuilder.GetScriptableObjectProxyCode(type)),
                    _ => (null, null)
                };

                if (attributeType != null)
                    Generate(attributeType, type.GetProxyName(), code);
            }

            UnityMatchPair[] pairs = inGameTypes
                .Select<Type, UnityMatchPair?>(type => type.IsUnityBaseEntity(out Type unityType) ? new(type, unityType) : null)
                .OfType<UnityMatchPair>()
                .ToArray();

            Generate(typeof(StaticProxy), StaticProxy.UnityMatchObjectsName, StaticProxyCodeBuilder.GetStaticUnityMatchComponentCode(pairs));

            ProxyGeneratorDebugger.DebugSucces();
    
            AssetDatabase.Refresh();
        }
        private static int GetPriority(Type type)
        {
            if (type.HasAttribute<InterfaceProxy>())
                return 1;
            return int.MaxValue;
        }
        private static void Generate(Type type, string fileName, string code)
        {
            File.WriteAllText(Path.Combine(ProxyDirectory.GetPath(type), $"{fileName}.cs"), code);

            ProxyGeneratorDebugger.DebugGeneratedProxy(fileName);
        }
    }
}
