namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Text;

    public static class StringBuilderProxyExtensions
    {
        public static void SetAutogeneratedMark(this StringBuilder stringBuilder) => stringBuilder.AppendLine($"//{ProxyGenerator.AutogeneratedMark}. DO NOT EDIT.");
        public static void SetUnityComponentBody(this StringBuilder stringBuilder, Type unityType, Type interfaceType)
        {
            string interfaceFullName = interfaceType.FullName;
            string unityFullName = unityType.FullName;

            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    [UnityEngine.SerializeField] private {unityFullName} _unityObject;");
            stringBuilder.AppendLine($"    public {interfaceFullName} ToPoco() => UnityIceFebruary.UnityMethods.Upsert<{unityFullName}, {interfaceFullName}>(_unityObject);");
            stringBuilder.AppendLine("}");
        }
        public static void SetAverageBody(this StringBuilder stringBuilder, Type type, Type toPocoType = null, string toPocoAdditionalKeys = null)
        {
            stringBuilder.AppendLine("{");

            ParameterInfo[] parameters = type.GetConstructors().First().GetParameters();
            List<string> parametersNames = new();

            foreach (ParameterInfo parameterInfo in parameters)
            {
                Type parameterType = parameterInfo.ParameterType;

                bool isArray = parameterType.IsProxyableArray(out Type arrayElementType);

                stringBuilder.Append("    [UnityEngine.");
                stringBuilder.Append(parameterType.IsInterface || isArray && arrayElementType.IsInterface ? "SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation" : "SerializeField");
                stringBuilder.Append("] private ");

                string parameterFieldName = $"_{parameterInfo.Name}";

                if (parameterType.IsProxyable())
                {
                    stringBuilder.Append(parameterType.GetProxyName());
                    parametersNames.Add($"{parameterFieldName} == null ? default : {parameterFieldName}.ToPoco()");
                }

                else if (isArray && arrayElementType.IsProxyable())
                {
                    string elementTypeName = arrayElementType.GetProxyName();

                    stringBuilder.Append($"{elementTypeName}[]");
                    parametersNames.Add($"System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select({parameterFieldName} ?? new {elementTypeName}[0], element => element.ToPoco()))");
                }

                else
                {
                    stringBuilder.Append(parameterType.FullName);
                    parametersNames.Add(parameterFieldName);
                }

                stringBuilder.AppendLine($" {parameterFieldName};");
            }

            stringBuilder.Append($"    public ");

            string typeName = type.FullName;

            if (!string.IsNullOrWhiteSpace(toPocoAdditionalKeys))
                stringBuilder.Append($"{toPocoAdditionalKeys} ");

            stringBuilder.Append(toPocoType == null ? typeName : toPocoType.FullName);
            stringBuilder.Append($" ToPoco() => new {typeName}({string.Join(", ", parametersNames)}");
            stringBuilder.AppendLine(");");
            stringBuilder.AppendLine("}");
        }
    }
}
